### PR TITLE
[dom daint tsa] Fix name of Libgpg-error

### PR DESCRIPTION
**Pull request by teojgo**

### CODE REVIEW

**Comment by teojgo** [comment]
retest this please

**Comment by teojgo** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
The error on DOm is the following:
```
ERROR: Missing dependencies: gcc/8.3.0 (no easyconfig file or existing module found)
```

**Review by lucamar — APPROVED** [review]
Thanks @teojgo

**Pull request merged**
