### PR TITLE
[kesch] First working Python 3.6.1 with gmvolf/17.02 EB recipe for MeteoSwiss

### PR DESCRIPTION
**Pull request by kraushm**
Following packages are included:

 - setuptools 36.2.0
 - pip 9.0.1
 - nose 1.3.7
 - numpy 1.13.1
 - scipy 0.19.1
 - mpi4py 2.0.0
 - Cython 0.26
 - six 1.10.0
 - virtualenv 15.1.0
 - matplotlib 2.0.2
 - pandas 0.20.3
 - datashape 0.5.2
 - Glymur 0.8.10
 - Jasper 0.1
 - XlsxWriter 0.9.8
 - xarray 0.9.6
 - watchdog 0.8.3
 - toolz 0.8.2
 - sympy 1.1
 - spyder 3.1.4
 - seaborn 0.8
 - pyproj 1.9.5.1
 - pykdtree 1.2.2
 - graphviz 0.8
 - inotify 0.2.8

Other packages requested are currently in the file (but commented out). I am currently checking, whether these packages can be supported. 
Packages like netCDF and HDF5 are considered to be put in separate modules.

### CODE REVIEW

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Comment by gppezzi** [comment]
retest this please

**Comment by kraushm** [comment]
retest this please

**Comment by kraushm** [comment]
Python 3.6.2 was successfully built on KeschTDS, therefore, this pull request is obsolete.

**Pull request closed without merging**
