### PR TITLE
Adding R 3.4.0

### PR DESCRIPTION
**Pull request by jirikuncar**

### CODE REVIEW

**Comment by gppezzi** [comment]
@jirikuncar did you check the open pull request #179 ? We would like to test Rmpi before merging that one, but we can consider to merge your recipe in case Rmpi does not work.

Thanks anyway for the contribution.

**Comment by gppezzi** [comment]
ok to test

**Comment by jirikuncar** [comment]
@gppezzi feel free to amend it. I just created it since I need R 3.4.0 for testing [1] of remote IR kernel.

--
[1] https://gist.github.com/jirikuncar/e4958e2c386e070d53b23985e28a4a49

**Comment by jirikuncar** [comment]
Should I close it as duplicate?

**Comment by gppezzi** [comment]
PR #179 is already merged so I'm closing this one. Feel free to re-open if #179 does not solve your issue.

**Pull request closed without merging**
