### PR TITLE
cdo/nco on daint

### PR DESCRIPTION
**Pull request by jgphpc**
[RT25765: cdo on daint does not support netcdf4](https://webrt.cscs.ch/Ticket/Display.html?id=25765)
[RT25801](https://webrt.cscs.ch/Ticket/Display.html?id=25801)
[RT26025](https://webrt.cscs.ch/Ticket/Display.html?id=26025)

### CODE REVIEW

**Comment by gppezzi** [comment]
I saw a couple of positive user feedback on this new recipe, should we deploy it on production or do you prefer to wait for other users? 

Please update the production list if you wish to make it available to all users.

**Comment by jgphpc** [comment]
I will wait and then i will update the jenkins script.

**Comment by jgphpc** [comment]
# daint-gpu :ok:
* https://jenkins.cscs.ch/job/ProductionEBtestingPR-gpu/42/label=daint103/console

# daint-mc :ok:
* https://jenkins.cscs.ch/view/ProductionEB/job/ProductionEBtestingPR-mc/18/label=daint102/console

**Comment by jgphpc** [comment]
@lucamar merge pf

**Comment by jgphpc** [comment]
== CDO/1.7.2-CrayGNU-2016.11 is already installed (module found), skipping

**Comment by jgphpc** [comment]
retest this please

**Comment by jgphpc** [comment]
retest this please (eb --force)

**Comment by jgphpc** [comment]
retest this please

**Comment by jgphpc** [comment]
test this please

**Comment by gppezzi** [comment]
ok to test

**Comment by jgphpc** [comment]
ok to test

**Comment by jgphpc** [comment]
retest this please

**Comment by jgphpc** [comment]
retest this please (https://github.com/janinko/ghprb/issues/150)

**Pull request merged**
