### PR TITLE
[dom-gpu, daint-gpu] PyExtensions-py2: use standard python{pymajver}

### PR DESCRIPTION
**Pull request by henrique**
python2 only

### CODE REVIEW

**Comment by henrique** [comment]
good catch Eirini, thx
looking at pythonpackage.py it looks like we shouldn't set the requirements for cray-python, as it takes it directly from sys.version_info, and it works fine without it:
```
ls /apps/daint/UES/dealmeih/easybuild/software/IPython/5.7.0-CrayGNU-19.10-python2/lib/python2.7/site-packages/
backcall/                              ipython_genutils/                      pickleshare-0.7.4-py2.7.egg            site.py
backcall-0.1.0-py2.7.egg-info          ipython_genutils-0.2.0-py2.7.egg-info  prompt_toolkit-1.0.15-py2.7.egg        site.pyc
decorator-4.3.0-py2.7.egg/             jedi-0.12.0-py2.7.egg/                 ptyprocess/                            traitlets/
easy-install.pth                       parso-0.2.1-py2.7.egg/                 ptyprocess-0.6.0-py2.7.egg-info        traitlets-4.3.2-py2.7.egg-info
enum34-1.1.6-py2.7.egg                 pathlib2-2.3.5-py2.7.egg/              Pygments-2.2.0-py2.7.egg/              wcwidth-0.1.7-py2.7.egg
IPython/                               pexpect/                               scandir-1.10.0-py2.7-linux-x86_64.egg  
ipython-5.7.0-py2.7.egg-info           pexpect-4.6.0-py2.7.egg-info           simplegeneric-0.8.1-py2.7.egg 
```

**Comment by henrique** [comment]
thanks for the comments @ekouts 
tests passing
unnecessary and unused variables removed

**Comment by ekouts** [comment]
The recipes lgtm. Sorry for giving feedback in pieces but I just noticed that `PyExtensions-2.7.15.6-CrayGNU-19.10.eb` is still in the production lists. Since we archive the old modules we should remove them from `7.0.UP01-19.10-gpu`, `7.0.UP01-19.10-gpu-dom`, `7.0.UP01-19.10-mc` and `7.0.UP01-19.10-mc-dom`, right? You don't have to wait again for jenkins to pass the.

**Comment by lucamar** [comment]
We can remove the old recipe from the production lists in a new pull request: the modules will still be available on the systems, unless we remove them manually as user `jenscscs` though.
> `PyExtensions-2.7.15.6-CrayGNU-19.10.eb` is still in the production lists. Since we archive the old modules we should remove them from `7.0.UP01-19.10-gpu`, `7.0.UP01-19.10-gpu-dom`, `7.0.UP01-19.10-mc` and `7.0.UP01-19.10-mc-dom`, right?

**Pull request merged**
