### PR TITLE
[dom-mc] CP2K with TC 19.03 (mc)

### PR DESCRIPTION
**Pull request by kraushm**

### CODE REVIEW

**Comment by vkarak** [comment]
@kraushm Perhaps you have to open a Jira case

**Comment by lucamar** [comment]
@vkarak I have created https://jira.cscs.ch/browse/MAINT-35

**Comment by kraushm** [comment]
It just seems to miss some deps. This should be fixed once another PR is merged with these deps, e. g. Boost.

**Comment by lucamar** [comment]
@kraushm Also the patch file was missing, since it takes the `name` and `version` of the recipe. I'm fixing it in my branch and I'll pull the changes.

**Pull request merged**
