### PR TITLE
[dom] Updated ipyparallel recipe for cdt/20.06 and production lists 

### PR DESCRIPTION
**Pull request by lucamar**
The new recipe will use the updated toolchain and Python templates.

### CODE REVIEW

**Comment by lucamar** [comment]
The build of the dependency `jupyterlab-1.1.1-CrayGNU-20.06-batchspawner.eb` failed while processing the extension `ipyparaview`:
see https://jenkins.cscs.ch/blue/organizations/jenkins/TestingEB/detail/TestingEB/3936/pipeline

The error is reported in the log file `/scratch/snx3000tds/jenscscs/TestingEB/dom-gpu/a8976d6-3936/tmp/eb-Lpcv2l/easybuild-jupyterlab-1.1.1-20200806.102452.teSap.log`:
```
    Installing build dependencies with npm.  This may take a while...
    npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    npm ERR! code E404
    npm ERR! 404 Not Found - GET https://registry.npmjs.org/@jupyterlab%2fobservables - Not found
    npm ERR! 404
    npm ERR! 404  '@jupyterlab/observables@^2.4.0' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
    npm ERR! 404 It was specified as a dependency of '@jupyterlab/services'
    npm ERR! 404
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /users/jenscscs/.npm/_logs/2020-08-06T08_43_48_441Z-debug.log
```

**Comment by henrique** [comment]
retest this please

**Comment by henrique** [comment]
retest this please

**Comment by henrique** [comment]
it looks like the npm repo was down again, hopefully it should work this time

**Comment by lucamar** [comment]
Thanks @henrique, the download and the build has now completed successfully.

**Pull request merged**
