### PR TITLE
[dom-gpu] fixing h5py-py3

### PR DESCRIPTION
**Pull request by jgphpc**

### CODE REVIEW

**Comment by jfavre** [comment]
why not adding sanity checks for all h5py recipes similar to:

sanity_check_commands = [(python3', "-c 'import %(namelower)s'")]

**Comment by teojgo** [comment]
@jgphpc you can also upgrade to the newest version of h5py, 2.7.1

**Comment by jgphpc** [comment]
retest this please

**Comment by victorusu** [comment]
retest this please

**Comment by victorusu** [comment]
retest this please

**Comment by victorusu** [comment]
retest this please

**Comment by victorusu** [comment]
retest this please

**Comment by victorusu** [comment]
retest this please

**Comment by victorusu** [comment]
retest this please

**Comment by victorusu** [comment]
retest this please

**Comment by gppezzi** [comment]
retest this please

**Pull request merged**
