### PR TITLE
[dom daint eiger pilatus tsa] Add recipe for ReFrame version 4.3.3

### PR DESCRIPTION
**Pull request by jenkins-cscs**

### CODE REVIEW

**Comment by lucamar** [comment]
Ok to test

**Comment by lucamar** [comment]
Can we merge this request @ekouts and @teojgo?

**Comment by lucamar** [comment]
The test build failed on Pilatus as the system is currently unavailable

**Comment by lucamar** [comment]
Can we merge this request @ekouts and @teojgo?

**Comment by teojgo** [comment]
@lucamar yes, you can proceed

**Review by teojgo — APPROVED** [review]

**Pull request merged**
