### PR TITLE
mfiles for perftools/645

### PR DESCRIPTION
**Pull request by jgphpc**
Modulefiles for technical reviews:

## daint-gpu
* /apps/daint/UES/jenkins/6.0.UP02/gpu/easybuild/software/perftools-cscs/

## daint-mc
* /apps/daint/UES/jenkins/6.0.UP02/mc/easybuild/software/perftools-cscs/

I will update the jenkins scripts when perftools/6.4.5 is installed on daint

### CODE REVIEW

**Comment by jgphpc** [comment]
retest this please.

**Comment by jgphpc** [comment]
Waiting for perftools/6.4.5 installation on daint.

**Comment by jgphpc** [comment]
retest this please.

**Comment by jgphpc** [comment]
All checks have passed :+1:

**Comment by lucamar** [comment]
Why not using the same naming convention that we have adopted for EasyBuild recipes with `versionsuffix` including `cudaversion`? 
E.g.:
`perftools-base-cscs-645cuda.eb` ->  `perftools-base-cscs-645-cuda-8.0.eb`
`perftools-base-cscs-645nogpu.eb` ->  `perftools-base-cscs-645.eb`

**Comment by jgphpc** [comment]
Because perftools supports any of cuda (cuda7 and cuda8).
Because we agreed that `nogpu` that more clear than `nothing`.

**Comment by gppezzi** [comment]
Regardless of what you decide to use as version suffix, you should use the dash as separator:
```
perftools-base-cscs-645-cuda.eb
perftools-base-cscs-645-nogpu.eb
```

While you fix this, you could also fix the old versions (that do not follow the current naming scheme).

**Comment by jgphpc** [comment]
nocuda means no cuda but openacc maybe ?
nogpu means nocuda & noopenacc

**Pull request merged**
