### PR TITLE
[daint dom fulen kesch leone] Update EasyBuild-custom modulefile and remove easyconfig

### PR DESCRIPTION
**Pull request by lucamar**
Adding `$::env(USER)` in the buildpath and tmpdir of systems that do not define `XDG_RUNTIME_DIR`. 

I have also removed the recipe `EasyBuild-custom/EasyBuild-custom-cscs.eb` as it is outdated and it should not be used to create the `EasyBuild-custom/cscs` modulefile anymore, since `production.sh`  links the hard-coded `EasyBuild-custom/cscs` module.

### CODE REVIEW

**Comment by lucamar** [comment]
For `fulen` I had to set `XDG_RUNTIME_DIR` manually, as it is not defined on the system:
```
    setenv XDG_RUNTIME_DIR                      /dev/shm/$::env(USER)
```
In principle we could use this approach on `leone` as well, avoiding to define a separate `if` later in the modulefile. I could not set it to `/tmp/$::env(USER)`, since `/tmp` has limited space available on `fulen`; I could not use `/run/user` either, since users are not allowed to create folders there:
```
$ mkdir /run/user/$USER
mkdir: cannot create directory ‘/run/user/lucamar’: Permission denied
```

**Comment by lucamar** [comment]
@victorusu Do we still need to define `XDG_CONFIG_DIRS`?
```
setenv XDG_CONFIG_DIRS                          $::env(EB_CUSTOM_REPOSITORY)
```

**Comment by lucamar** [comment]
retest this please

**Comment by victorusu** [comment]
> @victorusu Do we still need to define `XDG_CONFIG_DIRS`?
> 
> ```
> setenv XDG_CONFIG_DIRS                          $::env(EB_CUSTOM_REPOSITORY)
> ```

@lucamar, I do not think so.

**Comment by victorusu** [comment]
> > @victorusu Do we still need to define `XDG_CONFIG_DIRS`?
> > ```
> > setenv XDG_CONFIG_DIRS                          $::env(EB_CUSTOM_REPOSITORY)
> > ```
> 
> @lucamar, I do not think so.

@lucamar, Yes! We still need to define it!

**Pull request merged**
