### PR TITLE
[dom daint eiger pilatus tsa] Add recipe for ReFrame version 4.2.1

### PR DESCRIPTION
**Pull request by jenkins-cscs**

### CODE REVIEW

**Comment by teojgo** [comment]
Ok to test

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
I will merge this pull request as soon as you approve it @ekouts and @teojgo

**Review by teojgo — APPROVED** [review]

**Pull request merged**
