### PR TITLE
[daint-gpu] Starting point for Reframe 2.18

### PR DESCRIPTION
**Pull request by lucamar**
I have updated the recipe `Python-bare` to release `3.7.3`, including extension versions, dependency `ncurses` updated to release `6.1`: `reframe-tests` still missing to complete the recipe of `reframe`.
I have removed dependency `bzip2`, since release `1.0.6` is now provided by any operating system.

### CODE REVIEW

**Comment by vkarak** [comment]
@lucamar I will provide the reframe-tests sources.

**Comment by vkarak** [comment]
retest this please

**Comment by lucamar** [comment]
@vkarak I have removed `WIP` from the tile of the pull request to test it

**Comment by lucamar** [comment]
retest this please

**Comment by vkarak** [comment]
Thanks @lucamar. I've seen that the `reframe-test-2.18` sources are already in place.

**Comment by lucamar** [comment]
The build of `Python-bare-3.7.3` failed with the error `ModuleNotFoundError: No module named '_ctypes'` (log `/scratch/snx3000/jenscscs/TestingEB/daint-gpu/ace1d04-2187/tmp/eb-qOx4yB/easybuild-Python-bare-3.7.3-20190627.151120.VtSMZ.log`).

**Comment by lucamar** [comment]
I have added `libffi` as `builddependency`, following the threads below:
https://bugs.python.org/issue31652
https://bugs.python.org/issue30090
In order to configure correctly the build, I needed to add the following `configoopts`:
```
configopts = ' --with-system-ffi CFLAGS="-I$EBROOTLIBFFI/lib/libffi-3.2.1/include" LDFLAGS="-L$EBROOTLIBFFI/lib64" '
```

**Pull request merged**
