### PR TITLE
[dom-mc] visit2123

### PR DESCRIPTION
**Pull request by jgphpc**

### CODE REVIEW

**Comment by jfavre** [comment]
compilation is failing because of a missing /usr/lib64/libGLU.so on the Dom compute nodes. I have opened an ops ticket to get it installed.

https://webrt.cscs.ch/Ticket/Display.html?id=28881

**Comment by lucamar** [comment]
@jfavre I have successfully built `libxml2` with `python 2.7`, if you wnat to have a try instead of using the operating system libraries:`libxml2-2.9.4-CrayGNU-17.08-python2`

**Comment by jfavre** [comment]
retest this please

**Comment by jfavre** [comment]
I just did a temporary build in my private area on daint to give the Users a temporary workaround until a merge is done.

/scratch/snx1600/jfavre/daint/software/Visit/2.12.3-CrayGNU-17.08/easybuild/easybuild-Visit-2.12.3-20171004.162201.log

**Comment by jgphpc** [comment]
jenkins could not download visit-2.12.3.tar.gz

Add

```
# In order to use the pre-downloaded version use the source below
sources = ['/apps/common/UES/easybuild/sources/%(nameletterlower)s/%(name)s/' + SOURCELOWER_TAR_GZ]
```

in Visit-2.12.3-CrayGNU-17.08.eb

**Comment by jfavre** [comment]
retest this please

**Pull request merged**
