### PR TITLE
[dom] Add support for ZeroMQ-4.2.2 on CrayGNU-17.08

### PR DESCRIPTION
**Pull request by teojgo**

### CODE REVIEW

**Comment by jgphpc** [comment]
This is new ZeroMQ right ? Can you explain the motivation here please ?

**Comment by teojgo** [comment]
ZeroMQ is a dependency for PyZMQ which is one of the dependencies of IPython.

**Comment by teojgo** [comment]
retest this please

**Comment by lucamar** [comment]
Build number 553 on Jenkins succeeded:
https://jenkins.cscs.ch/job/TestingEB/553/label=dom/console

**Comment by teojgo** [comment]
@lucamar Build 553 succeeded.  Should I retest?

**Pull request merged**
