### PR TITLE
[daint] Reframe 2.6 easyconfig for craype/17.08

### PR DESCRIPTION
**Pull request by vkarak**

### CODE REVIEW

**Comment by vkarak** [comment]
retest this please

**Comment by lucamar** [comment]
The list of build is very long, probably you need to pull the changes in master to your branch.

**Comment by vkarak** [comment]
I am bit confused. I thought we were supposed to do a pull request to the `craype/17.08` branch. Should I branch off master and do a PR there? The only thing is that `Python-bare/.3.6.2` is not yet on master.

**Comment by lucamar** [comment]
You should do a pull request to the master: you can start from what you already did in `craype/17.08`.

**Comment by vkarak** [comment]
Ok, I'll do one there.

**Pull request closed without merging**
