### PR TITLE
[daint-gpu] Update jupyterlab-1.1.1-CrayGNU-18.08.eb

### PR DESCRIPTION
**Pull request by twrobinson**
Pull request add julia kernel support. Work in progress!

### CODE REVIEW

**Comment by twrobinson** [comment]
restest this please

**Comment by lucamar** [comment]
@twrobinson Is this pull request still relevant? You have neither provided any description, nor requested a review.

**Comment by twrobinson** [comment]
retest this please

**Comment by twrobinson** [comment]
Hi @lucamar , thanks for checking. As it isn't currently possible to convert a standard pull request to a draft pull request, and [WIP] prevents tests, I figured that not requesting anyone to review was the best way.

**Comment by twrobinson** [comment]
retest this please

**Comment by twrobinson** [comment]
Closed to align JLab with 1.1.1 in production on Daint. Julia integration will proceed with a new PR.

**Pull request closed without merging**
