### PR TITLE
[daint-gpu, dom-gpu] fix ParaView Cinema crashing

### PR DESCRIPTION
**Pull request by jfavre**
ParaView Cinema is part of the in-situ support needed for the Viz class of May 10

### CODE REVIEW

**Comment by jfavre** [comment]
addresses https://jira.cscs.ch/browse/AVAILAPPS-55

**Review by lucamar — APPROVED** [review]
Thanks @jfavre

**Comment by jfavre** [comment]
The build has failed but this is not under my control. Please assist me. TIA

== COMPLETED: Installation ended successfully (took 34 mins 0 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000tds/jenscscs/TestingEB/dom-gpu/c0d4eb9-5981/software/ParaView/5.10.1-CrayGNU-21.09-EGL/easybuild/easybuild-ParaView-5.10.1-20220506.221230.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /scratch/snx3000tds/jenscscs/TestingEB/dom-gpu/c0d4eb9-5981/tmp/eb-fde1z203/easybuild-h5c_4u8h.log* have been removed.
== Temporary directory /scratch/snx3000tds/jenscscs/TestingEB/dom-gpu/c0d4eb9-5981/tmp/eb-fde1z203 has been removed.

 Builds ended on Fri May  6 22:12:30 CEST 2022 (elapsed time is 2044 s : 0h 34m 4s) 

[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
ERROR: Timeout after 10 minutes
ERROR: Error fetching remote repo 'origin'

**Comment by jfavre** [comment]
retest this please

**Pull request merged**
