### PR TITLE
Adding lowercase naming scheme (for kesch)

### PR DESCRIPTION
**Pull request by gppezzi**
This is an attempt to answer the insisting MCH request to have lowercase module files. 

Here's how to test this:

```
$ export PYTHONPATH=$PYTHONPATH:/path/to/production
$ eb --avail-module-naming-schemes
List of supported module naming schemes:
	CategorizedHMNS
	CategorizedModuleNamingScheme
	HierarchicalMNS
	LowercaseModuleNamingScheme
	EasyBuildMNS
	MigrateFromEBToHMNS
$ export EASYBUILD_MODULE_NAMING_SCHEME=LowercaseModuleNamingScheme
```

### CODE REVIEW

**Comment by lucamar** [comment]
I tried to test it on Piz Daint, after loading the EasyBuild environment as usual, but I get an error if I run `eb --show-config`:
```
export EASYBUILD_PREFIX=/apps/daint/UES/sandbox/lucamar/easybuild
export EB_CUSTOM_REPOSITORY=/users/lucamar/production/easybuild
export PYTHONPATH=$PYTHONPATH:$EB_CUSTOM_REPOSITORY 
export EASYBUILD_MODULE_NAMING_SCHEME=LowercaseModuleNamingScheme
module load daint-gpu 
module load EasyBuild-custom/cscs 
eb --show-config
ERROR: Failed to parse configuration options: "Found problems validating the options: Selected module naming scheme 'LowercaseModuleNamingScheme' is unknown: {'HierarchicalMNS': <class 'easybuild.tools.module_naming_scheme.hierarchical_mns.HierarchicalMNS'>, 'EasyBuildMNS': <class 'easybuild.tools.module_naming_scheme.easybuild_mns.EasyBuildMNS'>, 'MigrateFromEBToHMNS': <class 'easybuild.tools.module_naming_scheme.migrate_from_eb_to_hmns.MigrateFromEBToHMNS'>, 'CategorizedHMNS': <class 'easybuild.tools.module_naming_scheme.categorized_hmns.CategorizedHMNS'>, 'CategorizedModuleNamingScheme': <class 'easybuild.tools.module_naming_scheme.categorized_mns.CategorizedModuleNamingScheme'>}"
```

**Comment by gppezzi** [comment]
````

**Comment by lucamar** [comment]
The lowercase naming scheme configuration of EasyBuild worked for me on Kesch:
```
keschln-0003:~$ eb CMake-3.8.1.eb
== temporary log file in case of crash /dev/shm/lucamar/easybuild/stage/tmp/eb-y4U8T9/easybuild-MNgyt1.log
== processing EasyBuild easyconfig /users/lucamar/production/easybuild/easyconfigs/c/CMake/CMake-3.8.1.eb
== building and installing cmake/3.8.1...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file(s) /apps/daint/UES/sandbox/lucamar/easybuild/software/cmake/3.8.1/easybuild/easybuild-CMake-3.8.1-20170711.162725.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /dev/shm/lucamar/easybuild/stage/tmp/eb-y4U8T9/easybuild-MNgyt1.log* have been removed.
== Temporary directory /dev/shm/lucamar/easybuild/stage/tmp/eb-y4U8T9 has been removed.
lucamar@keschln-0003:~$ module avail cmake

----------------------------------------------- /apps/daint/UES/sandbox/lucamar/easybuild/modules/all ------------------------------------------------
cmake/3.8.1
```

**Comment by gppezzi** [comment]
Thanks for the review. While waiting to merge this upstream (https://github.com/easybuilders/easybuild-framework/pull/2269), we've manually patched our local EB installations (3.2.1 and 3.3.0) to add this class.

I'm merging this, though we still have an issue on Daint when adding this class through a tweaked `$PYTHONPATH`...

**Pull request merged**
