### PR TITLE
[pilatus] VASP 6.3.0

### PR DESCRIPTION
**Pull request by lucamar**
I provide the recipe of the latest VASP release with CPE 21.12.

### CODE REVIEW

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
```
Cannot contact pilatus: java.lang.InterruptedException
```

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
```
Cannot contact pilatus: java.lang.InterruptedException
```

**Comment by lucamar** [comment]
retest this please

**Review by rsarm — APPROVED** [review]

**Pull request merged**
