### PR TITLE
[dom] pe1708 mympipingpong

### PR DESCRIPTION
**Pull request by jgphpc**

### CODE REVIEW

**Comment by jgphpc** [comment]
Refers to:
* https://github.com/hpcugent/mympingpong/issues/14
* https://github.com/hpcugent/mympingpong/issues/11


[test_links](https://portal.cray.com/apex/viewcase?Id=50033000017qsEBAAY) is probably a better test than mympipingpong

**Comment by jgphpc** [comment]
Tested on dom-mc with:

* srun -Cmc -t10 --nodes=6 --ntasks-per-node=12  `mympingpong -i 20 -n 2000 -f $PWD`

72c_12cpn

* Postprocess with:

```
easy_install --user pip
export PATH=$PATH:$HOME/.local/bin
pip install --user h5py
./mympingpong.git/bin/mympingponganalysis.py -f *.h5
open *.png
```

**Comment by jgphpc** [comment]
@lucamar i can't find why jenkins fails when all builds pass

**Comment by lucamar** [comment]
retest this please

**Pull request merged**
