### PR TITLE
PyRegression/2.0.1

### PR DESCRIPTION
**Pull request by gppezzi**
@vkarak let us know when this is ready

@jgphpc After running the Jenkins project, make sure that the default is updated to  2.0.1

### CODE REVIEW

**Comment by vkarak** [comment]
Sometime later today, it will be ready. I'll let you know.

**Comment by vkarak** [comment]
The 2.0.1 is released. You can check that it is properly installed by checking `run_regression.py --version`.

**Comment by jgphpc** [comment]
ok to test

**Comment by jgphpc** [comment]
retest this please

**Comment by jgphpc** [comment]
retest this please

**Pull request merged**
