### PR TITLE
Change from CRAYPE_NETWORK_TARGET to system name check

### PR DESCRIPTION
**Pull request by victorusu**
This PR is about how we define if the system is a CRAY or not

### CODE REVIEW

**Comment by victorusu** [comment]
retest this please

**Comment by gppezzi** [comment]
Don't expect this test to pass (EasyBuild-custom is used by jenkins, so we have chicken&egg problem).

**Comment by lucamar** [comment]
We need to find another variable, see my comment in #224

**Comment by lucamar** [comment]
The title of the pull request has not matched `leone` and `monch`, due to an upper case letter in `Leone` and a typo in `month`.

**Comment by gppezzi** [comment]
@victorusu @lucamar Since the new CN from kesch breaks again the system auto-guessing, let's please stop doing that and use host names for identifiying kesch/dom/daint.

**Comment by lucamar** [comment]
I have added the check of the system name, taking into account `*esch*` compute nodes as well. 
The CI on Jenkis failed as expected, since I have removed system names from the pull request title.

**Comment by gppezzi** [comment]
I'm feeling lucky, so I'm merging this.

**Pull request merged**
