### PR TITLE
[dom-gpu vtk801

### PR DESCRIPTION
**Pull request by jgphpc**

### CODE REVIEW

**Comment by jgphpc** [comment]
retest this please

**Comment by jgphpc** [comment]
* VTK-8.0.1-CrayGNU-17.08-python2.eb 
* VTK-8.0.1-CrayGNU-17.08-python3.eb 
failed.

**Comment by jfavre** [comment]
retest this please

**Comment by jfavre** [comment]
retest this please

**Comment by victorusu** [comment]
Can you please merge this? The VTK builds passed. But since Jenkins got also other things inside that there were not in the PR. It failed.

**Pull request merged**
