### PR TITLE
[daint] Add easybuild recipes for PROJ and ecCodes for CrayGNU-19.10

### PR DESCRIPTION
**Pull request by gkuhl**
Adds two easybuild recipes for the CrayGNU-19.10 system:
* PROJ-4.9.3-CrayGNU-19.10.eb
* ecCodes-2.12.2-CrayGNU-19.10.eb

(PS: It's the first time a make a pull request here, so let me know if this is the wrong procedure.)

### CODE REVIEW

**Comment by gppezzi** [comment]
@gkuhl PRs are always welcome!

**Comment by gppezzi** [comment]
test this please

**Comment by gppezzi** [comment]
@gkuhl Thanks for the contribution. These recipes should now be available when you do module load `EasyBuild-custom/cscs`

**Comment by gkuhl** [comment]
@gppezzi Thanks for review and merge.

**Pull request merged**
