### PR TITLE
[daint-gpu] Major VTK upgrade

### PR DESCRIPTION
**Pull request by jfavre**
== COMPLETED: Installation ended successfully (took 16 mins 42 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/VTK/9.1.0-CrayGNU-20.11-EGL-python3/easybuild/easybuild-VTK-9.1.0-20211107.104509.log

Release notes: https://gitlab.kitware.com/vtk/vtk/-/blob/master/Documentation/release/9.1.md

### CODE REVIEW

**Comment by jfavre** [comment]
@lucamar I don't understand why you already did the merge since the build had failed. I was in the middle of fixing the missing dependencies.

**Comment by lucamar** [comment]
@jfavre I merged #2516 after approving it, since [the corresponding build succeeded](https://jenkins.cscs.ch/blue/organizations/jenkins/TestingEB/detail/TestingEB/5443/pipeline). 
I have not yet approved this pull request and I could not have merged it, since it is not all green: looking at the history of commits, I see that the same commit 82dcd8a starting with `[daint-gpu] ...` is also listed in #2516, therefore you have likely pushed the same recipe of this pull request also there.

**Comment by jfavre** [comment]
I seem to be in a deadlock. I cannot edit or delete the file VTK-9.1.0-CrayGNU-20.11-EGL-python3.eb from #2517 , and I do not want to change the same file in #2518 since it has the correct settings.
Further, I don't know what you mean asking if cmake 3.14.5 was not enough,sicne it is exactly what I used. So I have no specific requirements to use a more recent cmake.

**Comment by lucamar** [comment]
@jfavre I have updated the VTK recipe in #2518 to solve the conflict: please kindly check if the recipe `VTK-9.1.0-CrayGNU-20.11-EGL-python3.eb` that is added there is correct.

**Pull request merged**
