### PR TITLE
[dom daint] Make installpaths use 'jenkins'

### PR DESCRIPTION
**Pull request by teojgo**
* Replace `jenscscs` with `jenkins` at the installpaths
  of the production lists for dom/daint.

### CODE REVIEW

**Comment by jgphpc** [comment]
This link:
```
lrwxrwxrwx 1 karakasv csstaff 8 Jul 21  2017 /apps/dom/UES/jenscscs -> jenkins/
```
has been in place since the beginning of [daint-gpu](https://github.com/eth-cscs/production/commits/master/login/daint-gpu).

Can you give more details to why this is needed (for jenkins) ?

**Comment by jgphpc** [comment]
It would make sense to replace `/apps/daint` with `$APPS`

**Comment by teojgo** [comment]
> It would make sense to replace `/apps/daint` with `$APPS`

Should it make sense in the `installpath` or in the jenkins production script?

**Comment by jgphpc** [comment]
This pr is justified because `/apps/*/jenkins` ==  `/apps/*/jenscscs` but more importantly `/apps/daint` != `/apps/dom`

**Pull request merged**
