### PR TITLE
[dom-gpu] SIRIUS 6.5.1

### PR DESCRIPTION
**Pull request by simonpintarelli**
add SIRIUS v6.5.1 for GNU/Intel

### CODE REVIEW

**Comment by lucamar** [comment]
@simonpintarelli I have submitted #1526 to fix the download link

**Comment by simonpintarelli** [comment]
> @simonpintarelli I have submitted #1526 to fix the download link of `libxc-4.3.4`:
> 
> ```
> == FAILED: Installation ended unsuccessfully (build directory: /tmp/jenscscs/83c2b44gpu/libxc/4.3.4/CrayGNU-19.10): build failed (first 300 chars): Couldn't find file libxc-4.3.4.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /scratch/snx3000/jenscscs/daint102/workspace/TestingEB/easybuild/easyconfigs/l/libxc/l/libxc/libxc-4.3.4.tar.gz, /scratch/snx3000/jenscscs/daint102/workspace/TestingEB/easybuild/easyc (took 0 sec)
> ```
> 
> See https://jenkins.cscs.ch/blue/organizations/jenkins/TestingEB/detail/TestingEB/3207/pipeline for the full logfile.

@lucamar Thank you. I've noticed  yesterday that the link was not working. It did work from home, and it is also working now if I do wget on daint. My experience with tddft.org is that it was quite often offline.

**Comment by lucamar** [comment]
@simonpintarelli If you want to try the latest ELPA release, I have submitted #1527 (I have used it for CP2K 7.1)

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
I have updated the download link of `libxc` with `CrayIntel`, but now the same download error occurred for `libxc` with `CrayGNU`:
```
== FAILED: Installation ended unsuccessfully (build directory: /tmp/jenscscs/8e550bcgpu/libxc/4.3.4/CrayGNU-19.10): build failed (first 300 chars): Couldn't find file libxc-4.3.4.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /scratch/snx3000/jenscscs/daint103/workspace/TestingEB/easybuild/easyconfigs/l/libxc/l/libxc/libxc-4.3.4.tar.gz, /scratch/snx3000/jenscscs/daint103/workspace/TestingEB/easybuild/easyc (took 0 sec)
```

**Comment by lucamar** [comment]
I have succeeded to download manually `libxc` using the GitLab link from a compute node on the XC50, so I don't understand why the test is failing instead: 
```
salloc -C gpu  -p debug --time=00:05:00
srun wget https://gitlab.com/libxc/libxc/-/archive/4.3.4/libxc-4.3.4.tar.gz
--2020-03-12 18:22:30--  https://gitlab.com/libxc/libxc/-/archive/4.3.4/libxc-4.3.4.tar.gz
Resolving gitlab.com (gitlab.com)... 35.231.145.151
Connecting to gitlab.com (gitlab.com)|35.231.145.151|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16108629 (15M) [application/octet-stream]
Saving to: ‘libxc-4.3.4.tar.gz’
[...]
2020-03-12 18:22:37 (2.14 MB/s) - ‘libxc-4.3.4.tar.gz’ saved [16108629/16108629]
```

**Comment by lucamar** [comment]
I have submitted #1528 to address the issue of `libxc` with `CrayGNU`.

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Pull request merged**
