### PR TITLE
Quantum espresso with perftools-cscs/645-nogpu

### PR DESCRIPTION
**Pull request by lucamar**
Setting OpenMP flag to `-qopenmp` for CrayIntel and fixing some issues with compile flags using sed syntax.

### CODE REVIEW

**Comment by jgphpc** [comment]
* grep 'creating the CrayPat-instrumented executable' /apps/daint/UES/jenkins/daint-gpu-jenkins-testPR/software/QuantumESPRESSO/5.4.0-CrayIntel-2016.11-pat-645-nogpu/easybuild/easybuild-QuantumESPRESSO-5.4.0-20170414.173754.log |grep pw.x
> INFO: creating the CrayPat-instrumented executable 'pw.x' (sample_profile) ...OK 

* grep 'creating the CrayPat-instrumented executable' /apps/daint/UES/jenkins/daint-gpu-jenkins-testPR/software/QuantumESPRESSO/6.1.0-CrayIntel-2016.11-pat-645-nogpu/easybuild/easybuild-QuantumESPRESSO-6.1.0-20170414.174741.log |grep pw.x
> INFO: creating the CrayPat-instrumented executable 'pw.x' (sample_profile) ...OK

**Comment by jgphpc** [comment]
Where can i find ausurf.in ? https://madra.cscs.ch/scs/PyRegression/blob/master/checks/apps/espresso/espresso_check.py#L21

**Comment by jgphpc** [comment]
My attempt to run fails with:

```
/opt/intel/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64/libifport.so.5: undefined symbol: for _ifcore_version
```

Do you get the same ?

**Comment by lucamar** [comment]
After the reboot of Piz Daint on May 4th the error message changed, see `/scratch/snx3000/lucamar/espresso/slurm-1525273.out`:
```
Submitting from daint101 (job ID 1525273)
Log file      : espresso.log
1 nodes, 12 tasks per node (12), 2 cpus per task, 12 total tasks

CrayPat/X:  Version 6.4.5 Revision 87dd5b8  01/23/17 15:37:24
/apps/daint/UES/sandbox/lucamar/easybuild/software/QuantumESPRESSO/6.1.0-CrayIntel-2016.11-pat-645-nogpu/bin/pw.x: relocation error: /apps/daint/UES/sandbox/lucamar/easybuild/software/QuantumESPRESSO/6.1.0-CrayIntel-2016.11-pat-645-nogpu/bin/pw.x: symbol kmp_aligned_malloc, version VERSION not defined in file libiomp5.so with link time reference
```

**Comment by lucamar** [comment]
As the perftools instrumented QuantumESPRESSO 6.1.0 is working when built without EasyBuild, I will close this pull request.

**Pull request closed without merging**
