### PR TITLE
[eiger] tweaks to enable h5part, run-time python, and hdf5_HL

### PR DESCRIPTION
**Pull request by jfavre**
this fixes 3 things:

HDF5_HL libs are not getting installed
cray-python module is not loaded for run-time
H5part was missing

### CODE REVIEW

**Comment by jfavre** [comment]
the build is successful on eiger. see /capstor/scratch/cscs/jenscscs/TestingEB/eiger/c619c57-6622/software/Visit/3.4.1-cpeGNU-23.12/easybuild/easybuild-Visit-3.4.1-20240724.155737.log
and fails on pilatus (could it be lack of memory)?
Do I need to dig some more or can it be merged since it is successful on eiger? @lucamar

**Comment by lucamar** [comment]
The build failed with the error below, reported in the log file `/capstor/scratch/cscs/jenscscs/TestingEB/pilatus/c619c57-6622/tmp/eb-z3wnjcim/easybuild-Visit-3.4.1-20240724.151812.DangP.log` mentioned in the [output of TestingEB](https://jenkins.cscs.ch/blue/organizations/jenkins/TestingEB/detail/TestingEB/6622/pipeline):
```
CMake Warning at CMake/FindZlib.cmake:56 (message):
  VISIT_ZLIB_DIR not set.
Call Stack (most recent call first):
  CMake/SetUpThirdParty.cmake:554 (include)
  CMakeLists.txt:928 (include)

CMake Error at CMake/FindZlib.cmake:63 (message):
  VisIt requires lib z and it could not be found.
Call Stack (most recent call first):
  CMake/SetUpThirdParty.cmake:554 (include)
  CMakeLists.txt:928 (include)
```

**Comment by jfavre** [comment]
> The build failed with the error below, reported in the log file `/capstor/scratch/cscs/jenscscs/TestingEB/pilatus/c619c57-6622/tmp/eb-z3wnjcim/easybuild-Visit-3.4.1-20240724.151812.DangP.log` mentioned in the [output of TestingEB](https://jenkins.cscs.ch/blue/organizations/jenkins/TestingEB/detail/TestingEB/6622/pipeline):
> 
> ```
> CMake Warning at CMake/FindZlib.cmake:56 (message):
>   VISIT_ZLIB_DIR not set.
> Call Stack (most recent call first):
>   CMake/SetUpThirdParty.cmake:554 (include)
>   CMakeLists.txt:928 (include)
> 
> CMake Error at CMake/FindZlib.cmake:63 (message):
>   VisIt requires lib z and it could not be found.
> Call Stack (most recent call first):
>   CMake/SetUpThirdParty.cmake:554 (include)
>   CMakeLists.txt:928 (include)
> ```
> 
> In my experience, sometimes `CMake` does not find some libraries depending on the system. It would be safer to add the CMake variable `VISIT_ZLIB_DIR` as suggested by the warning message printed in the log file right before the error.

indeed, this is exactly what the build wrapper of Visit does, if it does not fail earlier. This error on pilatus is not about zlib (which gets built earlier) but about the fact that the cmake config file was not created because of an earlier failure. as a matter of fact, I have not touched any options related to zlib since the beginning and it compiles fine on eiger (with user jenscscs, or with my personal account). using my account, I am already using the module with
module load cpeGNU
source /opt/cray/pe/cpe/23.12/restore_lmod_system_defaults.sh
module use /capstor/scratch/cscs/jfavre/eiger/modules/all
module load Toolchain/cpeGNU/23.12/Visit/3.4.1

I will now redo it with my account on pilatus

**Comment by jfavre** [comment]
the build on pilatus can fail in different ways. The latest I have tried is that it fails on ospray, because of a timeout in downloading a dependency;

on eiger and on my laptop, the following command takes less than 1 second:
`wget https://github.com/oneapi-src/oneTBB/releases/download/v2021.10.0/oneapi-tbb-2021.10.0-lin.tgz`
on pilatus, it times out and creates the failure of the build.
Should I create a ticket for timeout errors on pilatus?

**Comment by lucamar** [comment]
Thanks for testing @jfavre: let's exclude Pilatus from the test until we clarify the timeouts: unfortunately, it is not possible to either select or exclude a login node explicitly. It would be helpful if you could report the timeout on `pilatus-ln001`. 
Furthermore, please note `TestingEB` runs on compute nodes, so if you want to reproduce a failure, you need to allocate one. In the past, I noticed as well that downloads might fail: however, the recent upgrade introduced additional limitations (see [SD-61794](https://jira.cscs.ch/browse/SD-61794)).

**Comment by lucamar** [comment]
retest this please

**Comment by jfavre** [comment]
building on pilatus-ln002 was successful:

== COMPLETED: Installation ended successfully (took 39 mins 20 secs)
== Results of the build can be found in the log file(s) /capstor/scratch/cscs/jfavre/eiger/software/Visit/3.4.1-cpeGNU-23.12/easybuild/easybuild-Visit-3.4.1-20240724.183549.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /run/user/1100/tmp/eb-yv2k4kg7/easybuild-eigt0ykv.log* have been removed.
== Temporary directory /run/user/1100/tmp/eb-yv2k4kg7 has been removed.
jfavre@pilatus-ln002:~/production/easybuild/easyconfigs/v/Visit>

**Review by lucamar — APPROVED** [review]
Thanks @jfavre

**Pull request merged**
