### PR TITLE
[daint-gpu] New Theano version / performance improvements

### PR DESCRIPTION
**Pull request by mschoengens**

### CODE REVIEW

**Comment by mschoengens** [comment]
retest please

**Comment by gppezzi** [comment]
Are you planning to update the production list or should we merge only the recipes?

**Comment by gppezzi** [comment]
retest this please

**Comment by gppezzi** [comment]
@mschoengens would you mind re-doing your PR from a clean version of the master branch?

There's something funky with this branch, I see the same commit twice with different hashes. Did you do a rebase? I tried to sync with master, so it could be my fault as well.

**Comment by mschoengens** [comment]
Yes, I rebased from master. Let me try to clean up the commit history.

**Pull request merged**
