### PR TITLE
[dom] Update dismissed lists

### PR DESCRIPTION
**Pull request by lucamar**
I have moved outdated lists and system links to the folder `dismissed`: please check if that is correct.

### CODE REVIEW

**Review by teojgo — APPROVED** [review]
lgtm

**Comment by kraushm** [comment]
I took the liberty to move back `MCH-PE20.06` (current production list) back to the `jenkins-builds` folder.

**Review by kraushm — APPROVED** [review]
lgtm.

**Review by victorusu — APPROVED** [review]
`lgtm`

**Pull request merged**
