### PR TITLE
[daint] Remove python variables from ParaView

### PR DESCRIPTION
**Pull request by ekouts**

### CODE REVIEW

**Comment by jfavre** [comment]
Well done @ekouts . Thanks

**Comment by ekouts** [comment]
@jfavre I only changed the python variables, but I just remembered you had an open PR ( #1619 ) fixing one of the recipes in order for them to build on dom as well. Should we make similar fixes in all the recipes? I only put daint as a target

**Comment by jfavre** [comment]
LGTM

**Comment by jfavre** [comment]
I'll review the recipe for Dom later since its environment is in constant change. "constant change". Is this an oxymoron?

**Pull request merged**
