### PR TITLE
[daint-gpu] QE-Sirius with perftools-lite

### PR DESCRIPTION
**Pull request by lucamar**
I provide the EasyBuild recipe to build the instrumented version of QuantumESPRESSO-SIRIUS, as described in https://user.cscs.ch/access/report. 
Testing with `AUSURF112` failed, see `/scratch/snx3000/lucamar/qe-sirius`.

### CODE REVIEW

**Comment by lucamar** [comment]
The build failed with the following error on the compute node:
```
FAILED 
/usr/bin/ld: cannot find -lcupti
```
See the log file `/scratch/snx3000/jenscscs/TestingEB/daint-gpu/d2faad1-4214/tmp/eb-QJFSR7/easybuild-QuantumESPRESSO-SIRIUS-6.5-rc4-20200917.182704.URMNj.log`, reby ferenced https://jenkins.cscs.ch/blue/organizations/jenkins/TestingEB/detail/TestingEB/4214/pipeline.

Nonetheless, I have managed to build successfully the recipe on the login node.

**Comment by lucamar** [comment]
I confirm that the build works on the login node:
```
== COMPLETED: Installation ended successfully (took 3 min 51 sec)
== Results of the build can be found in the log file(s) /apps/daint/UES/sandbox/lucamar/easybuild/software/QuantumESPRESSO-SIRIUS/6.5-rc4-CrayIntel-20.08-cuda-pat/easybuild/easybuild-QuantumESPRESSO-SIRIUS-6.5-rc4-20200918.090030.log
```

**Comment by toxa81** [comment]
@lucamar What shall we do about not being able to compile on compute node? It seems that libcupti can't be found by a linker. I have no clue who is in charge of fixing it.

**Comment by lucamar** [comment]
Thanks for the feedback @toxa81: I will cross-check the build on a compute node and ask a system administrator if the failure is confirmed.

**Comment by lucamar** [comment]
I have managed to build on a compute node with my username:
```
== 2020-09-18 11:34:37,220 easyblock.py:280 INFO This is EasyBuild 4.2.2 (framework: 4.2.2, easyblocks: 4.2.2) 
on host nid02593.
```
Therefore, I assume that there was an issue in mounting the file system with the `cupti` library on the node used by Jenkins.

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
The new version of QE-SIRIUS (with `SIRIUS 6.5.6`) and `perftools-lite` fails with the following error: 
```
environment.f90(26): error #7002: Error in opening the compiled module file.  Check IN
CLUDE paths.   [COMMAND_LINE_OPTIONS]
  USE command_line_options, ONLY : nmany_
------^
environment.f90(26): error #6580: Name in only-list does not exist or is not accessibl
e.   [NMANY_]
  USE command_line_options, ONLY : nmany_
-----------------------------------^
environment.f90(243): error #6406: Conflicting attributes or multiple declaration of n
ame.   [NMANY_]
    WRITE( stdout, '(5X,"Fft bands division:     nmany     = ",I7)' ) nmany_
----------------------------------------------------------------------^
environment.f90(261): error #6406: Conflicting attributes or multiple declaration of n
ame.   [NMANY_]
    WRITE( stdout, '(5X,"Fft bands division:     nmany     = ",I7)' ) nmany_
----------------------------------------------------------------------^
```

**Comment by lucamar** [comment]
I close this pull request, due to the new QE-SIRIUS provided by #1960

**Pull request closed without merging**
