### PR TITLE
[dom-mc] vis-modules-1708

### PR DESCRIPTION
**Pull request by jfavre**
visualization modules for the september update

### CODE REVIEW

**Comment by gppezzi** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
Several missing dependencies that are not yet in production on Dom, e.g.:
```
ERROR: Irresolvable dependencies encountered: Boost/1.63.0-CrayGNU-17.08-Python-3.6.2, h5py/2.7.0-CrayGNU-17.08-Python-3.6.2-serial, CMake/.3.9.1
```

**Comment by jfavre** [comment]
using cray-python causes the following error on import

import libxml2
ImportError: No module named libxml2ImportError

**Comment by lucamar** [comment]
@jfavre I'm modifying the EasyBuild recipe of `libxml2` in the master branch with `cray-python`

**Comment by lucamar** [comment]
`libxml2` wants to add the corresponding Python package, which is not straightforward with `cray-python`:
```
/usr/bin/install: cannot create regular file '/opt/python/17.06.1/lib/python2.7/site-packages/drv_libxml2.py': Permission denied
/usr/bin/install: cannot create regular file '/opt/python/17.06.1/lib/python2.7/site-packages/libxml2.py': Permission denied
```

**Comment by jfavre** [comment]
version 2.9.4 (if no the older version) has a config option

 --with-python-install-dir=DIR
                          install Python bindings in DIR

this is perhaps our quickest way to get there.

**Comment by jgphpc** [comment]
Moving into 3 new PR:
* https://github.com/eth-cscs/production/pull/320
* https://github.com/eth-cscs/production/pull/321
* https://github.com/eth-cscs/production/pull/322

**Pull request closed without merging**
