### PR TITLE
[daint] Update Boost recipes to 20.11 toolchains

### PR DESCRIPTION
**Pull request by msimberg**
Also add them to production lists.

I haven't tested the CrayCCE recipe (I'm assuming the two others will work just fine). Hoping to have CI tell me if I've done something wrong.

### CODE REVIEW

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
Does someone know how the boost recipe actually does the configuration before building (boost uses b2 but I see no mention of it in the recipe)? Is there some other place I can place the `--with-toolset=clang` option for the CrayCCE build?

**Comment by teojgo** [comment]
> Does someone know how the boost recipe actually does the configuration before building (boost uses b2 but I see no mention of it in the recipe)? Is there some other place I can place the `--with-toolset=clang` option for the CrayCCE build?

Can you try `toolset = 'clang'`? It is one parameter accepted by the EasyBlock for Boost.

**Comment by msimberg** [comment]
> > Does someone know how the boost recipe actually does the configuration before building (boost uses b2 but I see no mention of it in the recipe)? Is there some other place I can place the `--with-toolset=clang` option for the CrayCCE build?
> 
> Can you try `toolset = 'clang'`? It is one parameter accepted by the EasyBlock for Boost.

Thanks @teojgo, I didn't know about that option. It seems to have worked nicely!

I tend to forget to add the recipes to the production lists, but this time I remembered. Do they look ok? bzip and zlib don't need to be added, right?

**Comment by teojgo** [comment]
> > > Does someone know how the boost recipe actually does the configuration before building (boost uses b2 but I see no mention of it in the recipe)? Is there some other place I can place the `--with-toolset=clang` option for the CrayCCE build?
> > 
> > 
> > Can you try `toolset = 'clang'`? It is one parameter accepted by the EasyBlock for Boost.
> 
> Thanks @teojgo, I didn't know about that option. It seems to have worked nicely!
> 
> I tend to forget to add the recipes to the production lists, but this time I remembered. Do they look ok? bzip and zlib don't need to be added, right?

Yeap they seem fine now. You don't need to include bzip and zlib in the production lists. They are going to be built as hidden modules since Boost depends on them.

**Pull request merged**
