### PR TITLE
[dom daint pilatus tsa] Add recipe for ReFrame CSCS tests version 23.09

### PR DESCRIPTION
**Pull request by jenkins-cscs**

### CODE REVIEW

**Comment by lucamar** [comment]
Ok to test

**Comment by teojgo** [comment]
retest this please

**Comment by lucamar** [comment]
Hi @teojgo and @ekouts, it this request ready to be merged?

**Review by ekouts — APPROVED** [review]
Thanks @lucamar , looks good to me.

**Pull request merged**
