### PR TITLE
[daint] Addition of CDO-CrayIntel recipe

### PR DESCRIPTION
**Pull request by omlins**

### CODE REVIEW

**Comment by omlins** [comment]
retest this please

**Comment by omlins** [comment]
Installation output
```
omlins@daint102:~/0_tickets/30378/production/easybuild/easyconfigs/c/CDO> eb CDO-1.9.0-CrayIntel-17.08.eb -r
== temporary log file in case of crash /dev/shm/omlins/easybuild/stage/tmp/eb-og5ZsK/easybuild-V7URvF.log
== resolving dependencies ...
== processing EasyBuild easyconfig /users/omlins/0_tickets/30378/production/easybuild/easyconfigs/c/CDO/CDO-1.9.0-CrayIntel-17.08.eb
== building and installing CDO/1.9.0-CrayIntel-17.08...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file(s) /scratch/snx3000/omlins/software/CDO/1.9.0-CrayIntel-17.08/easybuild/easybuild-CDO-1.9.0-20180115.185626.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /dev/shm/omlins/easybuild/stage/tmp/eb-og5ZsK/easybuild-V7URvF.log* have been removed.
== Temporary directory /dev/shm/omlins/easybuild/stage/tmp/eb-og5ZsK has been removed.
```

**Comment by jgphpc** [comment]
tested with /scratch/snx3000/piccinal/RT/30378/STATSJG/CDO_INTEL/rt30378

**Comment by jgphpc** [comment]
THKS @omlins

**Comment by jgphpc** [comment]
will be added to the production list if it fixes the issue.

**Pull request merged**
