### PR TITLE
[daint-gpu] jupyterlab-1.2.16 with Julia 1.5.0 for CrayGNU-19.10

### PR DESCRIPTION
**Pull request by omlins**
This is marked as WIP for the moment as JupyterLab will be released on Wednesday for with Julia 1.4.2.

### CODE REVIEW

**Comment by lucamar** [comment]
Is it still work in progress, @omlins?

**Comment by omlins** [comment]
Operations did not release JupyterLab with Julia 1.4.2 yesterday. Thus, we will release JupyterLab with Julia 1.5.0 in the next maintenance (when Tim is back), i.e. we need the recipes of this PR.

**Comment by omlins** [comment]
retest this please

**Comment by omlins** [comment]
Closing this pull request to replace it with another one.

**Pull request closed without merging**
