### PR TITLE
[dom-gpu] jupyterlab 1.2.16 with julia 1.5.0 (PE 20.08)

### PR DESCRIPTION
**Pull request by omlins**

### CODE REVIEW

**Comment by omlins** [comment]
this is just to undo the comment change again.

**Comment by omlins** [comment]
@twrobinson if you think merging will cause any issues right now we can wait of course

**Comment by omlins** [comment]
@twrobinson: More precisely, I mean if rebuilding on Dom causes any issues, we can wait merging or wait forcing the rebuild on Dom.

**Comment by omlins** [comment]
I marked it as WIP for this reason.

**Review by twrobinson — APPROVED** [review]
ok to merge

**Comment by omlins** [comment]
retest this please

**Comment by omlins** [comment]
@lucamar can you merge; then we are done with the cleanup...

**Pull request merged**
