### PR TITLE
[eiger pilatus] Fix system name

### PR DESCRIPTION
**Pull request by lucamar**
I update the system name match in the EasyBuild custom module addressing Eiger and Pilatus and removing outdated matches of dismissed systems: this should fix the error of [ProductionEB](https://jenkins.cscs.ch/view/Production/job/ProductionEB) on Eiger (see my comment in #2790 ).

### CODE REVIEW

**Review by teojgo — APPROVED** [review]

**Review by ekouts — APPROVED** [review]
It looks fine as it is, but would it be possible to use `/etc/xthostname`'s content, since it seems to be in all our systems?

**Comment by lucamar** [comment]
> It looks fine as it is, but would it be possible to use `/etc/xthostname`'s content, since it seems to be in all our systems?

Thanks @ekouts, `/etc/xthostname` is defined on Dom, Eiger, Pilatus and Piz Daint, but not on Tsa: anyway we are not addressing the latter within `EasyBuild-custom`, so I think we can ignore it unless @kraushm has any objections.

**Comment by lucamar** [comment]
I have included a command to match the hostnames of Arolla and Tsa, @kraushm. I have removed Escha/Kesch and Fulen that no longer exist.

**Review by kraushm — APPROVED** [review]
Thanks @lucamar, lgtm.

**Pull request merged**
