### PR TITLE
Paraview with EGL

### PR DESCRIPTION
**Pull request by jfavre**
ParaView with EGL. Succesfully tested on Dom. It prevents the crashing of Render windows when closing/reopening a root 3D window.

### CODE REVIEW

**Comment by jfavre** [comment]
/opt/cray/nvidia/default/lib64/libOpenGL.so is still missing on daint and that explains the failure. We will hold on this MR until the upgrade of the NVIDIA driver.

**Comment by gppezzi** [comment]
retest this please

**Comment by gppezzi** [comment]
Waiting for @jfavre 's  patch or his approval to merge this version.

**Comment by jfavre** [comment]
currently doing a local build on daint101...
Stay tuned.

**Comment by jfavre** [comment]
I have successfully tested my private build on daint, with EGL.
It also eliminates the root 3D window closing/reopening bug of ParaView, so it's a good improvement to ParaView for Production users.

**Comment by gppezzi** [comment]
Thanks @jfavre

**Pull request merged**
