### PR TITLE
[dom-gpu] ParaView the GPU version with updates for 18.08

### PR DESCRIPTION
**Pull request by jfavre**
ParaView for GPU

### CODE REVIEW

**Comment by gppezzi** [comment]
retest this please

**Comment by jfavre** [comment]
retest this please

**Comment by gppezzi** [comment]
```
[dom-gpu] == FAILED: Installation ended unsuccessfully (build directory: /tmp/jenscscs/7b61673/ParaView/5.5.2/CrayGNU-18.08-EGL): build failed (first 300 chars): Can't guess patchlevel from patch /scratch/snx1600tds/jenscscs/TestingEB/dom-gpu/7b61673-829/sources/p/ParaView/nek5000reader.patch: no testfile line found in patch
[dom-gpu] == Results of the build can be found in the log file(s) /scratch/snx1600tds/jenscscs/TestingEB/dom-gpu/7b61673-829/tmp/eb-wKTsEw/easybuild-ParaView-5.5.2-20180827.134805.iPCCt.log
```

**Comment by jfavre** [comment]
retest this please

**Pull request merged**
