### PR TITLE
[daint-mc] Updated OF recipes

### PR DESCRIPTION
**Pull request by kraushm**
Updating OpenFOAM recipes for CrayGNU 20.11

### CODE REVIEW

**Comment by kraushm** [comment]
retest this please

**Comment by kraushm** [comment]
retest this please

**Comment by lucamar** [comment]
The build fails with this error:
```
    ERROR: ParaView not found in /scratch/snx3000/jenscscs/TestingEB/daint-mc/8496e92-4770/software/OpenFOAM/5.0-CrayGNU-20.11/ThirdParty-5.x/platforms/linux64Gcc/ParaView-5.4.0
```
The version of ParaView in production has changed in the meanwhile to `5.9.0`:
```
$ module load daint-mc 
$ module avail ParaView

--------------------------------- /apps/daint/UES/jenkins/7.0.UP02-20.11/mc/easybuild/modules/all ----------------------------------
ParaView/5.9.0-CrayGNU-20.11-OSMesa-python3(default)
```

**Review by lucamar — APPROVED** [review]
Thanks @kraushm

**Pull request merged**
