### PR TITLE
[daint-gpu] Fix srcdir for Dycore-551f6b4 cdt-19.08

### PR DESCRIPTION
**Pull request by teojgo**

### CODE REVIEW

**Comment by lucamar** [comment]
@omlins I think that we can merge the pull request, what do you think?

**Review by lucamar — APPROVED** [review]
Thanks @teojgo

**Review by omlins — COMMENTED** [review]
@lucamar, I discussed it with Theo offline and I think you should decide together with him if this should be merged as you introduced this change.

**Comment by lucamar** [comment]
> @lucamar, I discussed it with Theo offline and I think you should decide together with him if this should be merged as you introduced this change going from 20.06 to 20.08.

I changed that line, since it was not working otherwise for me: as it worked also with the recipes that were built successful in this pull request, I think it is safe to merge it.

**Pull request merged**
