### PR TITLE
[dom-gpu] Add Julia 1.4.1 with MPI and CUDA packages

### PR DESCRIPTION
**Pull request by victorusu**
This PR adds support to the MPI package in the `juliapackages.py` file.

### CODE REVIEW

**Comment by omlins** [comment]
MPI unit tests successful on daint-gpu:
```
omlins@dom101:/scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10-cuda-10.1/extensions/packages/MPI/2F5CB/test> julia runtests.jl 
Running MPI.jl tests
srun: post_submit: 0, 1019973, 8
	SUCCESS: test_allgather.jl
srun: post_submit: 0, 1019973, 9
	SUCCESS: test_allgatherv.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 10
	SUCCESS: test_allreduce.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 11
	SUCCESS: test_alltoall.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 12
	SUCCESS: test_alltoallv.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 13
	SUCCESS: test_basic.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 14
	SUCCESS: test_bcast.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 15
	SUCCESS: test_cart_coords.jl
srun: post_submit: 0, 1019973, 16
	SUCCESS: test_cart_create.jl
srun: post_submit: 0, 1019973, 17
	SUCCESS: test_cart_get.jl
srun: post_submit: 0, 1019973, 18
	SUCCESS: test_cart_rank.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 19
	SUCCESS: test_cart_shift.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 20
	SUCCESS: test_comm.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 21
Test Summary: | Pass  Total
Test Summary: | Pass  Total
Test Summary: | Pass  Total
Test Summary: | Pass  Total
Non bitstype  |    1      1
Non bitstype  |    1      1
Non bitstype  |    1      1
Non bitstype  |    1      1
Test Summary: | Pass  Total
Compound type |   10     10
Test Summary: | Pass  Total
Compound type |   10     10
Test Summary: | Pass  Total
Compound type |   10     10
Test Summary: | Pass  Total
Compound type |   10     10
Test Summary: | Pass  Total
nested types  |   13     13
Test Summary: | Pass  Total
nested types  |   13     13
Test Summary: | Pass  Total
nested types  |   13     13
Test Summary: | Pass  Total
nested types  |   13     13
Test Summary:               | Pass  Total
PrimitiveType = Primitive16 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive16 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive16 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive16 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive24 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive24 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive24 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive24 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive80 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive80 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive80 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive80 |    2      2
Test Summary:             | Pass  Total
packed non-aligned tuples |    2      2
Test Summary:             | Pass  Total
packed non-aligned tuples |    2      2
Test Summary:             | Pass  Total
packed non-aligned tuples |    2      2
Test Summary:             | Pass  Total
packed non-aligned tuples |    2      2
Test Summary: | Pass  Total
0-sized type  |    1      1
Test Summary: | Pass  Total
0-sized type  |    1      1
Test Summary: | Pass  Total
0-sized type  |    1      1
Test Summary: | Pass  Total
0-sized type  |    1      1
	SUCCESS: test_datatype.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 22
	SUCCESS: test_dims_create.jl
srun: post_submit: 0, 1019973, 23
	SUCCESS: test_exscan.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 24
	SUCCESS: test_gather.jl
srun: post_submit: 0, 1019973, 25
	SUCCESS: test_gatherv.jl
srun: post_submit: 0, 1019973, 26
	SUCCESS: test_info.jl
srun: post_submit: 0, 1019973, 27
	SUCCESS: test_onesided.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 28
	SUCCESS: test_reduce.jl
srun: post_submit: 0, 1019973, 29
	SUCCESS: test_scan.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 30
	SUCCESS: test_scatter.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 31
	SUCCESS: test_scatterv.jl
srun: post_submit: 0, 1019973, 32
	SUCCESS: test_sendrecv.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 33
Test Summary: | Pass  Total
Test Summary: | Pass  Total
Test Summary: | Pass  Total
Test Summary: | Pass  Total
contiguous    |    2      2
contiguous    |    2      2
contiguous    |    2      2
contiguous    |    2      2
Test Summary: | Pass  Total
strided       |    2      2
Test Summary: | Pass  Total
strided       |    2      2
Test Summary: | Pass  Total
strided       |    2      2
Test Summary: | Pass  Total
strided       |    2      2
Test Summary:  | Pass  Total
dense subarray |    2      2
Test Summary:  | Pass  Total
dense subarray |    2      2
Test Summary:  | Pass  Total
dense subarray |    2      2
Test Summary:  | Pass  Total
dense subarray |    2      2
	SUCCESS: test_subarray.jl
srun: post_submit: 0, 1019973, 34
	SUCCESS: test_test.jl
srun: post_submit: 0, 1019973, 35
┌ Warning: Thread level requested = THREAD_MULTIPLE, provided = THREAD_SERIALIZED
└ @ MPI /scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10-cuda-10.1/extensions/packages/MPI/2F5CB/src/environment.jl:144
┌ Warning: Thread level requested = THREAD_MULTIPLE, provided = THREAD_SERIALIZED
└ @ MPI /scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10-cuda-10.1/extensions/packages/MPI/2F5CB/src/environment.jl:144
┌ Warning: Thread level requested = THREAD_MULTIPLE, provided = THREAD_SERIALIZED
└ @ MPI /scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10-cuda-10.1/extensions/packages/MPI/2F5CB/src/environment.jl:144
┌ Warning: Thread level requested = THREAD_MULTIPLE, provided = THREAD_SERIALIZED
└ @ MPI /scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10-cuda-10.1/extensions/packages/MPI/2F5CB/src/environment.jl:144
	SUCCESS: test_threads.jl
srun: post_submit: 0, 1019973, 36
	SUCCESS: test_universe_size.jl
srun: Job 1019973 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 1019973
srun: post_submit: 0, 1019973, 37
	SUCCESS: test_wait.jl
```

**Comment by omlins** [comment]
and also on daint-mc:
```
omlins@dom101:~> module load daint-mc
omlins@dom101:~> module load /scratch/snx3000tds/omlins/9_soft_install_julia_1_4/modules/all/Julia/1.4.1-CrayGNU-19.10
omlins@dom101:~> cd /scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10/extensions/packages/MPI/2F5CB/test/
omlins@dom101:/scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10/extensions/packages/MPI/2F5CB/test> salloc -Cmc -N4
salloc: Pending job allocation 1020004
salloc: post_submit: 0, 1020004, 4294967294
salloc: job 1020004 queued and waiting for resources
salloc: job 1020004 has been allocated resources
salloc: Granted job allocation 1020004
omlins@dom101:/scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10/extensions/packages/MPI/2F5CB/test> sr^C -n1 -N1 --pty bash 
omlins@dom101:/scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10/extensions/packages/MPI/2F5CB/test> julia runtests.jl 
Running MPI.jl tests
srun: post_submit: 0, 1020004, 0
	SUCCESS: test_allgather.jl
srun: post_submit: 0, 1020004, 1
	SUCCESS: test_allgatherv.jl
srun: post_submit: 0, 1020004, 2
	SUCCESS: test_allreduce.jl
srun: post_submit: 0, 1020004, 3
	SUCCESS: test_alltoall.jl
srun: post_submit: 0, 1020004, 4
	SUCCESS: test_alltoallv.jl
srun: post_submit: 0, 1020004, 5
	SUCCESS: test_basic.jl
srun: post_submit: 0, 1020004, 6
	SUCCESS: test_bcast.jl
srun: post_submit: 0, 1020004, 7
	SUCCESS: test_cart_coords.jl
srun: post_submit: 0, 1020004, 8
	SUCCESS: test_cart_create.jl
srun: post_submit: 0, 1020004, 9
	SUCCESS: test_cart_get.jl
srun: post_submit: 0, 1020004, 10
	SUCCESS: test_cart_rank.jl
srun: post_submit: 0, 1020004, 11
	SUCCESS: test_cart_shift.jl
srun: post_submit: 0, 1020004, 12
	SUCCESS: test_comm.jl
srun: post_submit: 0, 1020004, 13
Test Summary: | Pass  Total
Test Summary: | Pass  Total
Test Summary: | Pass  Total
Test Summary: | Pass  Total
Non bitstype  |    1      1
Non bitstype  |    1      1
Non bitstype  |    1      1
Non bitstype  |    1      1
Test Summary: | Pass  Total
Compound type |   10     10
Test Summary: | Pass  Total
Compound type |   10     10
Test Summary: | Pass  Total
Test Summary: | Pass  Total
Compound type |   10     10
Compound type |   10     10
Test Summary: | Pass  Total
nested types  |   13     13
Test Summary: | Pass  Total
nested types  |   13     13
Test Summary: | Pass  Total
nested types  |   13     13
Test Summary: | Pass  Total
nested types  |   13     13
Test Summary:               | Pass  Total
PrimitiveType = Primitive16 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive16 |    2      2
Test Summary:               | Pass  Total
Test Summary:               | Pass  Total
PrimitiveType = Primitive16 |    2      2
PrimitiveType = Primitive16 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive24 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive24 |    2      2
Test Summary:               | Pass  Total
Test Summary:               | Pass  Total
PrimitiveType = Primitive24 |    2      2
PrimitiveType = Primitive24 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive80 |    2      2
Test Summary:               | Pass  Total
PrimitiveType = Primitive80 |    2      2
Test Summary:               | Pass  Total
Test Summary:               | Pass  Total
PrimitiveType = Primitive80 |    2      2
PrimitiveType = Primitive80 |    2      2
Test Summary:             | Pass  Total
packed non-aligned tuples |    2      2
Test Summary:             | Pass  Total
packed non-aligned tuples |    2      2
Test Summary:             | Pass  Total
packed non-aligned tuples |    2      2
Test Summary:             | Pass  Total
packed non-aligned tuples |    2      2
Test Summary: | Pass  Total
Test Summary: | Pass  Total
0-sized type  |    1      1
0-sized type  |    1      1
Test Summary: | Pass  Total
0-sized type  |    1      1
Test Summary: | Pass  Total
0-sized type  |    1      1
	SUCCESS: test_datatype.jl
srun: post_submit: 0, 1020004, 14
	SUCCESS: test_dims_create.jl
srun: post_submit: 0, 1020004, 15
	SUCCESS: test_exscan.jl
srun: post_submit: 0, 1020004, 16
	SUCCESS: test_gather.jl
srun: post_submit: 0, 1020004, 17
	SUCCESS: test_gatherv.jl
srun: post_submit: 0, 1020004, 18
	SUCCESS: test_info.jl
srun: post_submit: 0, 1020004, 19
	SUCCESS: test_onesided.jl
srun: post_submit: 0, 1020004, 20
	SUCCESS: test_reduce.jl
srun: post_submit: 0, 1020004, 21
	SUCCESS: test_scan.jl
srun: post_submit: 0, 1020004, 22
	SUCCESS: test_scatter.jl
srun: post_submit: 0, 1020004, 23
	SUCCESS: test_scatterv.jl
srun: post_submit: 0, 1020004, 24
	SUCCESS: test_sendrecv.jl
srun: post_submit: 0, 1020004, 25
Test Summary: | Pass  Total
Test Summary: | Pass  Total
Test Summary: | Pass  Total
Test Summary: | Pass  Total
contiguous    |    2      2
contiguous    |    2      2
contiguous    |    2      2
contiguous    |    2      2
Test Summary: | Pass  Total
strided       |    2      2
Test Summary: | Pass  Total
strided       |    2      2
Test Summary: | Pass  Total
strided       |    2      2
Test Summary: | Pass  Total
strided       |    2      2
Test Summary:  | Pass  Total
dense subarray |    2      2
Test Summary:  | Pass  Total
dense subarray |    2      2
Test Summary:  | Pass  Total
Test Summary:  | Pass  Total
dense subarray |    2      2
dense subarray |    2      2
	SUCCESS: test_subarray.jl
srun: post_submit: 0, 1020004, 26
	SUCCESS: test_test.jl
srun: post_submit: 0, 1020004, 27
┌ Warning: Thread level requested = THREAD_MULTIPLE, provided = THREAD_SERIALIZED
└ @ MPI /scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10/extensions/packages/MPI/2F5CB/src/environment.jl:144
┌ Warning: Thread level requested = THREAD_MULTIPLE, provided = THREAD_SERIALIZED
└ @ MPI /scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10/extensions/packages/MPI/2F5CB/src/environment.jl:144
┌ Warning: Thread level requested = THREAD_MULTIPLE, provided = THREAD_SERIALIZED
└ @ MPI /scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10/extensions/packages/MPI/2F5CB/src/environment.jl:144
┌ Warning: Thread level requested = THREAD_MULTIPLE, provided = THREAD_SERIALIZED
└ @ MPI /scratch/snx3000tds/omlins/9_soft_install_julia_1_4/software/Julia/1.4.1-CrayGNU-19.10/extensions/packages/MPI/2F5CB/src/environment.jl:144
	SUCCESS: test_threads.jl
srun: post_submit: 0, 1020004, 28
	SUCCESS: test_universe_size.jl
srun: post_submit: 0, 1020004, 29
	SUCCESS: test_wait.jl
```

**Comment by victorusu** [comment]
Ciao @lucamar, since @omlins and I are involved in this PR, can you please approve it so that we can merge it?
The tests should fail due to the permission problem in the folder.
But this will be fixed when we set the `umask` in the production list.

**Comment by lucamar** [comment]
Sure @victorusu: I would try to re-trigger the build anyway, since the last one was trying to run on Piz Daint instead of Dom.

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
Sorry, I have commented the wrong pull request: the comment was meant for #1625

**Pull request merged**
