### PR TITLE
[dom] ipm pe/1708

### PR DESCRIPTION
**Pull request by jgphpc**

### CODE REVIEW

**Comment by jgphpc** [comment]
retest this

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
The builds succeeded in the gpu software stack but they were not run in the mc software stack, since the modulefiles were already found: the `$PREFIX`is in fact the same for the gpu and mc builds, a bug that needs to be addressed in `TestingEB`. See the output of the test for the details:
https://jenkins.cscs.ch/job/TestingEB/label=dom/420/console

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
The Jenkins project `TestingEB`now defines the EasyBuild prefix as `PREFIX/$ARCH`, where `$ARCH`can be `gpu`or `mc`, thus fixing the bug  that I have reported in my previous comment.

**Comment by lucamar** [comment]
This branch as well is not up to date with the master:
```
Current diff list by 'git diff origin/master..HEAD --name-only --oneline --no-merges --diff-filter=ACMRTUXB':
easybuild/cray_external_modules_metadata.cfg
easybuild/easyconfigs/i/IPM/IPM-2.0.6-Cray-17.08.patch
easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayCCE-17.08.eb
easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayGNU-17.08.eb
easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayIntel-17.08.eb
easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayPGI-17.08.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-CrayGNU-17.08.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-CrayIntel-17.08.eb
easybuild/easyconfigs/m/mxml/mxml-2.10-CrayGNU-17.08.eb
easybuild/easyconfigs/m/mxml/mxml-2.10-CrayIntel-17.08.eb
easybuild/easyconfigs/v/VMD/VMD-1.9.3-egl.eb
easybuild/easyconfigs/v/VMD/VMD-1.9.3-ogl.eb
easybuild/easyconfigs/v/Visit/Visit-2.12.0-CrayGNU-2016.11.eb
jenkins-builds/6.0.UP04-17.08-gpu
jenkins-builds/6.0.UP04-17.08-mc
```

**Pull request merged**
