### PR TITLE
[daint-mc] Jupyterlab 1.2.4 with IJulia 1.4.2

### PR DESCRIPTION
**Pull request by omlins**
This uses the latest JuliaExtensions module with CUDA.jl 1.2.0 and the latest versions of the other included Julia modules.
There is also a recipe for mc without CUDA.
Bumped JupyterLab version to 1.2.16. Otherwsie should be more or less equivalent to current 1.1.1. 
Bug with Safari browser constantly refreshing when multiple jupyterlab tabs are open is fixed with this release.

### CODE REVIEW

**Comment by omlins** [comment]
retest this please

**Comment by twrobinson** [comment]
retest this please

**Comment by twrobinson** [comment]
retest this please

**Comment by twrobinson** [comment]
I'm still getting "ValueError: Invalid file object: <_io.TextIOWrapper name=4 encoding='UTF-8'>" regularly. Rebuild tends to fix the issue.

**Comment by twrobinson** [comment]
retest this please

**Comment by twrobinson** [comment]
retest this please

**Comment by twrobinson** [comment]
Retest this please. Nearly ready to give up.

**Comment by twrobinson** [comment]
retest this please

**Comment by twrobinson** [comment]
retest this please ("cloning error" last time)

**Comment by twrobinson** [comment]
retest this please

**Pull request closed without merging**
