### PR TITLE
[dom-gpu] NAMD fix for dom-gpu with cdt/20.06

### PR DESCRIPTION
**Pull request by ChristopherBignamini**
Fixes UES-984

### CODE REVIEW

**Comment by ChristopherBignamini** [comment]
retest this please

**Comment by henrique** [comment]
Hey @ChristopherBignamini 
Thanks for the PR
perhaps you want to create a PR to push NAMD-2.13-CrayIntel-20.06-cuda.eb directly into master?
Jenkins will not be able to build such a large PR within the time limit

**Comment by ChristopherBignamini** [comment]
Hi @henrique ,
yes sure. Actually my changes are very limited: a new patch file and a line change in the easyconfig. I guess I'm doing something wrong, the instructions in UES-974 say to push to the experimental branch, right?

**Comment by henrique** [comment]
As we already merged some 20.06 stuff to master, I think it's easier to go directly onto it...
But yes, you can push to experimental if you prefer
In that case, we can test it by running ExperimentalEB manually
TestingEB (attached to the agent here) might not be able to build your code then

**Comment by ChristopherBignamini** [comment]
I've opened a new PR (https://github.com/eth-cscs/production/pull/1767) to push to master

**Pull request closed without merging**
