### PR TITLE
[daint-mc] Add deepmd-kit-1.1.4

### PR DESCRIPTION
**Pull request by rsarm**

### CODE REVIEW

**Comment by rsarm** [comment]
adding `--local_ram_resources=60000` to `bazel build` because the jenkins test creashed with
```
slurmstepd: error: Detected 1 oom-kill event(s) in step 21922566.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: nid00025: task 0: Out Of Memory
srun: Terminating job step 21922566.0
```

**Comment by lucamar** [comment]
Thanks for providing the package @rsarm: in the previous release `0.10.2`  that was addressed by an EasyBuild recipe there used to be also other executables together with `dp_ipi`: 
```
ls /apps/daint/UES/sandbox/lucamar/easybuild/software/DeePMD/0.10.2-CrayGNU-19.10/bin
dp_frz  dp_ipi  dp_mdnn  dp_test  dp_train
```
Do you know if they can still be built of have they been discontinued? 
I have also asked about a user of the code in CSCS RT #38858.

**Comment by rsarm** [comment]
The way deepmd is built has changed and I think now they put all the functionalities together through the executables `dp` and `dp_ipi`. Now one does `dp train ...` like here https://github.com/deepmodeling/deepmd-kit#write-the-input-script

**Comment by lucamar** [comment]
Thanks for your reply @rsarm: do you plan to make `deepmd` available in production or just as a recipe?

**Comment by rsarm** [comment]
@lucamar just a recipe. I did this for 38732

**Pull request merged**
