### PR TITLE
[daint-gpu] jupyterlab-1.2.16-CrayGNU-19.10-cuda-10.1-batchspawner.eb

### PR DESCRIPTION
**Pull request by twrobinson**
change a comment to force rebuild

### CODE REVIEW

**Comment by twrobinson** [comment]
No idea why this failed. I'm guessing a network failure or problem with pypi repo ("HTTP Error 503: Service Unavailable").

**Comment by twrobinson** [comment]
retest this please

**Comment by twrobinson** [comment]
retest this please

**Comment by twrobinson** [comment]
retest this please

**Review by omlins — APPROVED** [review]
approved to enable rebuilt - you need to undo it however once it works!

**Review by jgphpc — APPROVED** [review]

**Pull request merged**
