### PR TITLE
WIP: Theano for Python3 and newest PrgEnv.

### PR DESCRIPTION
**Pull request by mschoengens**
Building with eb works, however, loading the Theano Python module has an MPI error.

Setup:
```
module load daint-gpu
module use /apps/daint/UES/6.0.UP02/sandbox-ds/easybuild/haswell/modules/all/
module use ~/easybuild/daint/haswell/modules/all/
module load Theano/0.8.2-CrayGNU-2016.11-Python-3.5.2
```

The error:
```
python3
Python 3.5.2 (default, Nov 23 2016, 16:26:10)
[GCC 5.3.0 20151204 (Cray Inc.)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
[Mon Jan 30 14:55:09 2017] [unknown] Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(525):
MPID_Init(228).......: channel initialization failed
MPID_Init(611).......:  PMI2 init failed: 1
Aborted
```

### CODE REVIEW

**Comment by gppezzi** [comment]
Did you try this on a compute node and prefixing the command by 'srun'?

MPI subsystem is not working on login nodes and MPI-enabled python is known to fail there.

**Comment by gppezzi** [comment]
ok to test

**Comment by mschoengens** [comment]
Yes, you are right, the MPI for python is working on the compute nodes...

**Comment by gppezzi** [comment]
@mschoengens  do you really need to keep cuDNN-5.1.eb?

Is this still WIP?

**Comment by mschoengens** [comment]
@gppezzi: Still working on it: I am not 100% convinced that everything is working as expected..

**Comment by mschoengens** [comment]
@gppezzi I triple-checked, Theano is working with proper GPU support. If you have no further comments, the PR is ready to be merged.

**Pull request merged**
