### PR TITLE
[dom] Add R kernel to JupyterLab builds

### PR DESCRIPTION
**Pull request by twrobinson**
This PR adds an R kernel to JupyterLab, which has been requested by several users. The kernel is based on cray-R/3.6.3.1. The cray-R/4.x modules unfortunately do not have the necessary capabilities compiled into them in order to render content in Jupyter (a request has been made for future builds to include the necessary capabilities: png and cairo).
Testing results in SD-52208
Ready for review

### CODE REVIEW

**Comment by twrobinson** [comment]
retest this please

**Comment by twrobinson** [comment]
retest this please

**Review by lucamar — APPROVED** [review]
Thanks @twrobinson: let's use the new recipes that you have provided until we manage to use the default `cray-R` as a dependency, which would make automated updates easier

**Comment by lucamar** [comment]
The build on `dom-gpu` failed with the following error message:
```
RuntimeError: npm dependencies failed to install
See the log file for details:  /scratch/snx3000tds/jenscscs/TestingEB/dom-gpu/21714dd-5329/tmp/eb-_onsg6jo/jupyterlab-debug-0pmjwz32.log
Warning in install.packages("IRkernel", "/scratch/snx3000tds/jenscscs/TestingEB/dom-gpu/21714dd-5329/software/jupyterlab/2.2.10-CrayGNU-20.11-batchspawner-cuda/share/ir36",  :
  'lib = "/scratch/snx3000tds/jenscscs/TestingEB/dom-gpu/21714dd-5329/software/jupyterlab/2.2.10-CrayGNU-20.11-batchspawner-cuda/share/ir36"' is not writable
Error in install.packages("IRkernel", "/scratch/snx3000tds/jenscscs/TestingEB/dom-gpu/21714dd-5329/software/jupyterlab/2.2.10-CrayGNU-20.11-batchspawner-cuda/share/ir36",  : 
  unable to install packages
```

The log file of `npm` reports the following error downloading the package (might be temporary):
```
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@jupyterlab/celltags/-/celltags-2.2.8.tgz: Request failed \"502 Bad Gateway\"".
```

**Review by crystalfp — APPROVED** [review]
Approve

**Comment by twrobinson** [comment]
Thanks Luca, looks like failed network connectivity or similar. I'll run the whole thing again.

**Comment by twrobinson** [comment]
> The build on `dom-gpu` failed with the following error message:
> 
> ```
> RuntimeError: npm dependencies failed to install
> See the log file for details:  /scratch/snx3000tds/jenscscs/TestingEB/dom-gpu/21714dd-5329/tmp/eb-_onsg6jo/jupyterlab-debug-0pmjwz32.log
> Warning in install.packages("IRkernel", "/scratch/snx3000tds/jenscscs/TestingEB/dom-gpu/21714dd-5329/software/jupyterlab/2.2.10-CrayGNU-20.11-batchspawner-cuda/share/ir36",  :
>   'lib = "/scratch/snx3000tds/jenscscs/TestingEB/dom-gpu/21714dd-5329/software/jupyterlab/2.2.10-CrayGNU-20.11-batchspawner-cuda/share/ir36"' is not writable
> Error in install.packages("IRkernel", "/scratch/snx3000tds/jenscscs/TestingEB/dom-gpu/21714dd-5329/software/jupyterlab/2.2.10-CrayGNU-20.11-batchspawner-cuda/share/ir36",  : 
>   unable to install packages
> ```
> 
> The log file of `npm` reports the following error downloading the package (it might be a temporary issue):
> 
> ```
> [3/5] Fetching packages...
> error An unexpected error occurred: "https://registry.yarnpkg.com/@jupyterlab/celltags/-/celltags-2.2.8.tgz: Request failed \"502 Bad Gateway\"".
> ```

Built this time without any changes. Probably an issue with the interwebs.

**Pull request merged**
