### PR TITLE
[eiger, pilatus] adding FFmpeg v5 for eiger

### PR DESCRIPTION
**Pull request by jfavre**

### CODE REVIEW

**Comment by jfavre** [comment]
ERROR: libx264 not found
however the module exists and the library is there /apps/pilatus/UES/jenkins/1.4.0/software/x264/20191217-cpeGNU-21.12/lib/
so I don't have a clue.

**Comment by jfavre** [comment]
retest this please

**Comment by lucamar** [comment]
I think that the error reported by `TestingEB` is due to the issue described in [VCMSA-101](https://jira.cscs.ch/browse/VCMSA-101): as a matter of fact, the module `x264/20191217` is not available under the path of the default `cpeGNU/21.12`, which is loaded by Lmod instead of your local installpath with the module.

**Comment by jfavre** [comment]
> I think that the error reported by `TestingEB` is due to the issue described in [VCMSA-101](https://jira.cscs.ch/browse/VCMSA-101): as a matter of fact, the module `x264/20191217` is not available under the path of the default `cpeGNU/21.12`, which is loaded by Lmod instead of your local installpath with the module.

you are most likely right. Unfortunately, I don't have the competence to fix VCMSA-101.

**Comment by lucamar** [comment]
I will merge it, since you tested locally

**Pull request merged**
