### PR TITLE
[dom] FFmpeg for matplotlib animation or stand-alone video encoding

### PR DESCRIPTION
**Pull request by jfavre**
== COMPLETED: Installation ended successfully (took 18 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000tds/jfavre/daint/software/NASM/2.14.02-CrayGNU-20.08/easybuild/easybuild-NASM-2.14.02-20200909.075703.log
== Build succeeded for 1 out of 1

== COMPLETED: Installation ended successfully (took 1 min 20 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000tds/jfavre/daint/software/FFmpeg/4.2.2-CrayGNU-20.08/easybuild/easybuild-FFmpeg-4.2.2-20200909.073913.log
== Build succeeded for 1 out of 1

### CODE REVIEW

**Comment by jfavre** [comment]
this PR addresses https://webrt.cscs.ch/Ticket/Display.html?id=39964

**Review by lucamar — COMMENTED** [review]
Thanks @jfavre: does the module need to be visible or can it be hidden (EasyBuild flag `--hidden`)?

**Comment by jfavre** [comment]
> Thanks @jfavre: does the module need to be visible or can it be hidden (EasyBuild flag `--hidden`)?

the module needs to be visible to be used stand-alone.

**Comment by lucamar** [comment]
Thanks for your prompt feedback @jfavre: as discussed, a user needs to know the complete name to load a `hidden` module, therefore we merge the pull request as it is now. We can change it at a later stage though.

**Review by lucamar — APPROVED** [review]
Thanks @jfavre

**Pull request merged**
