### PR TITLE
[eiger] CDO, NCO and dependencies with 21.04

### PR DESCRIPTION
**Pull request by lucamar**
I provide the recipe of CDO and NCO with their dependencies for PE 21.04 on Eiger.

### CODE REVIEW

**Comment by lucamar** [comment]
I have removed the `checksum` verification, since I get two different strings:
```
$ sha256sum /scratch/e1000/jenscscs/TestingEB/eiger/8b175b1-4866/sources/c/CDO/cdo-1.9.10.tar.gz
78306b762bec19202ef1acdbdcdac848bd46d9de21fa5fc7055712f49a80af1d  /scratch/e1000/jenscscs/TestingEB/eiger/8b175b1-4866/sources/c/CDO/cdo-1.9.10.tar.gz

uan03:~$ wget https://code.mpimet.mpg.de/attachments/download/24638/cdo-1.9.10.tar.gz
uan03:~$ sha256sum cdo-1.9.10.tar.gz 
cc39c89bbb481d7b3945a06c56a8492047235f46ac363c4f0d980fccdde6677e  cdo-1.9.10.tar.gz
```
The website https://code.mpimet.mpg.de/projects/cdo/files reports the second one as correct, though.

**Comment by lucamar** [comment]
I cannot reproduce locally the failure in the configure step of `binutils-2.36.1-cpeGNU-21.04.eb`.

**Comment by lucamar** [comment]
The `binutils` issue disappeared, but now the download of the CDO tarball seems to be unreliable:
```
== FAILED: Installation ended unsuccessfully (build directory: /tmp/jenscscs/e261387/CDO/1.9.10/cpeGNU-21.04): build failed (first 300 chars): cmd "tar xzf /scratch/e1000/jenscscs/TestingEB/eiger/e261387-4872/sources/c/CDO/cdo-1.9.10.tar.gz" exited with exit code 2 and output:
gzip: stdin: not in gzip format
tar: Child returned status 1
```

**Comment by lucamar** [comment]
The build of `PROJ-7.2.1-CrayGNU-20.11.eb` failed: the file should be compiled on Piz Daint, in fact it was in this pull request by mistake. Therefore I have restored the version of the file from the master and it has being removed from the list of modified files.

**Review by kraushm — APPROVED** [review]
lgtm.

**Pull request merged**
