### PR TITLE
[daint-gpu] APEX profiler

### PR DESCRIPTION
**Pull request by toxa81**

### CODE REVIEW

**Comment by jgphpc** [comment]
could you provide a (very) simple example so we can add 1 check to reframe ?

**Comment by victorusu** [comment]
retest this please

**Comment by victorusu** [comment]
retest this please

**Comment by toxa81** [comment]
@jgphpc which kind of example?

**Comment by toxa81** [comment]
test this please

**Comment by toxa81** [comment]
[daint-gpu] == resolving dependencies ...
[daint-gpu] ERROR: Irresolvable dependencies encountered: OTF2/.2.1.1-CrayIntel-17.08

OTF2/.2.1.1-CrayIntel-17.08 was merged yesterday

**Comment by toxa81** [comment]
retest this please

**Comment by toxa81** [comment]
demo.cpp:
```
#include "apex_api.hpp"
#include <pthread.h>
#include <unistd.h>
#include <iostream>

using namespace apex;
using namespace std;

void* someThread(void* tmp)
{
  int* tid = (int*)tmp;
  char name[32];
  sprintf(name, "worker-thread#%d", *tid);
  register_thread(name);
  profiler* p = start((apex_function_address)someThread);
  sample_value("/threadqueue{locality#0/total}/length", 2.0);
  char counter[64];
  sprintf(counter, "/threadqueue{locality#0/%s}/length", name);
  sample_value(counter, 2.0);
  stop(p);
  exit_thread();
  return NULL;
}

int main (int argc, char** argv) {
  init(argv[0], 0, 1);
  cout << "APEX Version : " << version() << endl;
  profiler* p = start((apex_function_address)(main));
  pthread_t thread[2];
  int tid = 0;
  pthread_create(&(thread[0]), NULL, someThread, &tid);
  int tid2 = 1;
  pthread_create(&(thread[1]), NULL, someThread, &tid2);
  pthread_join(thread[0], NULL);
  pthread_join(thread[1], NULL);
  stop(p);
  finalize();
  return 0;
}
```
CC -std=c++11 demo.cpp  -lapex

export APEX_OTF2=1
export APEX_PROFILE=1
export APEX_SCREEN_OUTPUT=1

```
./a.out
Rank 0 of 1.
--
Built on: 10:13:56 Jul 17 2018
C++ Language Standard version : 201402
Intel Compiler version : Intel(R) C++ g++ 5.3 mode
APEX_DISABLE : 0
APEX_SUSPEND : 0
APEX_PAPI_SUSPEND : 0
APEX_PROCESS_ASYNC_STATE : 1
APEX_TAU : 0
APEX_OTF2 : 1
APEX_OTF2_TESTING : 0
APEX_OTF2_COLLECTIVE_SIZE : 1
APEX_POLICY : 1
APEX_MEASURE_CONCURRENCY : 0
APEX_MEASURE_CONCURRENCY_PERIOD : 1000000
APEX_SCREEN_OUTPUT : 1
APEX_PROFILE_OUTPUT : 0
APEX_CSV_OUTPUT : 0
APEX_TASKGRAPH_OUTPUT : 0
APEX_PROC_CPUINFO : 0
APEX_PROC_MEMINFO : 0
APEX_PROC_NET_DEV : 0
APEX_PROC_SELF_STATUS : 0
APEX_PROC_SELF_IO : 0
APEX_PROC_STAT : 1
APEX_PROC_PERIOD : 1000000
APEX_THROTTLE_CONCURRENCY : 0
APEX_THROTTLING_MAX_THREADS : 20
APEX_THROTTLING_MIN_THREADS : 1
APEX_THROTTLE_ENERGY : 0
APEX_THROTTLE_ENERGY_PERIOD : 1000000
APEX_THROTTLING_MAX_WATTS : 300
APEX_THROTTLING_MIN_WATTS : 150
APEX_PTHREAD_WRAPPER_STACK_SIZE : 0
APEX_OMPT_REQUIRED_EVENTS_ONLY : 0
APEX_OMPT_HIGH_OVERHEAD_EVENTS : 0
APEX_PIN_APEX_THREADS : 1
APEX_TASK_SCATTERPLOT : 0
APEX_TIME_TOP_LEVEL_OS_THREADS : 0
APEX_POLICY_DRAIN_TIMEOUT : 1000
APEX_PAPI_METRICS :
APEX_PLUGINS :
APEX_PLUGINS_PATH : ./
APEX_OUTPUT_FILE_PATH : ./
APEX_OTF2_ARCHIVE_PATH : OTF2_archive
APEX_OTF2_ARCHIVE_NAME : APEX
APEX Version : --
Built on: 10:13:56 Jul 17 2018
C++ Language Standard version : 201402
Intel Compiler version : Intel(R) C++ g++ 5.3 mode

Elapsed time: 0.00285155 seconds
Cores detected: 20
Worker Threads observed: 3
Available CPU time: 0.00855464 seconds

Counter                        : #samples |  minimum |    mean  |  maximum |   total  |  stddev
------------------------------------------------------------------------------------------------
/threadqueue{locality#0/tot... :        2   2.00e+00   2.00e+00   2.00e+00   4.00e+00   0.00e+00
/threadqueue{locality#0/wor... :        1   2.00e+00   2.00e+00   2.00e+00   2.00e+00   0.00e+00
/threadqueue{locality#0/wor... :        1   2.00e+00   2.00e+00   2.00e+00   2.00e+00   0.00e+00
------------------------------------------------------------------------------------------------

Timer                                                :  #calls  |    mean  |   total  |  % total
------------------------------------------------------------------------------------------------
UNRESOLVED /users/antonk/my_eb_scripts/xpress-ape... :        1   2.45e-04   2.45e-04      2.869
UNRESOLVED /users/antonk/my_eb_scripts/xpress-ape... :        2   2.30e-05   4.61e-05      0.538
                                           APEX Idle :                       8.26e-03     96.592
------------------------------------------------------------------------------------------------
                                        Total timers : 3
Closing OTF2 event files...
Writing OTF2 definition files...
Writing OTF2 Global definition file...
Writing OTF2 Node information...
Writing OTF2 Communicators...
Closing the archive...
done.
```

**Pull request merged**
