### PR TITLE
[dom-gpu] Updated recipes for PE 21.02

### PR DESCRIPTION
**Pull request by jenkins-cscs**

### CODE REVIEW

**Comment by lucamar** [comment]
I plan to trigger again `UpdateEB` before merging this pull request, since many failures should be temporary only: see  https://jira.cscs.ch/browse/UES-1503

**Review by jgphpc — APPROVED** [review]

**Comment by jgphpc** [comment]
retest this please

**Comment by jgphpc** [comment]
```
slurmstepd: error: *** STEP 1442557.0 ON nid00000 CANCELLED AT 2021-06-06T15:22:13 DUE TO TIME LIMIT ***
```

**Comment by lucamar** [comment]
The build that could not complete on time was `TensorFlow`, however it has been built successfully by `UpdateEB` on Dom with `cdt-cuda/21.02`:
```
dom101:~$ module load daint-gpu/21.02 
dom101:~$ module avail TensorFlow

------------------------------------- /apps/dom/UES/jenkins/7.0.UP02/21.02/dom-gpu/modules/all --------------------------------------
TensorFlow/2.4.0-CrayGNU-21.02
```
Therefore I think that we can merge this pull request.

**Pull request merged**
