### PR TITLE
[daint-gpu] Create jupyterlab-2.2.9-CrayGNU-20.11-batchspawner-cuda.eb

### PR DESCRIPTION
**Pull request by twrobinson**
This is a beta test

### CODE REVIEW

**Review by lucamar — APPROVED** [review]
Looks good @twrobinson, is it ready to be merged?

**Review by victorusu — APPROVED** [review]
`lgtm`

**Comment by victorusu** [comment]
@twrobinson, this is still a draft, should we merge make it a proper PR and merge it?

**Comment by twrobinson** [comment]
Please keep as a draft.

**Comment by twrobinson** [comment]
postponing this

**Pull request closed without merging**
