### PR TITLE
[dom-gpu] CP2K with 19.03 (cuda 10)

### PR DESCRIPTION
**Pull request by kraushm**

### CODE REVIEW

**Comment by vkarak** [comment]
@kraushm Shouldn't we open a Jira case for this?

**Comment by lucamar** [comment]
@vkarak I have created https://jira.cscs.ch/browse/MAINT-35

**Comment by vkarak** [comment]
@lucamar I meant about the failure. If it's a real build failure, we should open an issue.

**Comment by lucamar** [comment]
@vkarak No, it's justrelated to missing dependencies and patches, as I commented in https://jira.cscs.ch/browse/MAINT-9

**Comment by lucamar** [comment]
@vkarak I'll upload the missing files to complete the build

**Comment by lucamar** [comment]
@vkarak Please accept the changes to merge the pull request

**Pull request merged**
