### PR TITLE
[daint-gpu] Update system_wide.cfg

### PR DESCRIPTION
**Pull request by twrobinson**
Remove dask from list of hidden modules. @rsarm and @gppezzi, I'm not sure why it was in this list (the modules themselves are not hidden on dom and daint - well some are and some aren't) - let me know. thanks

### CODE REVIEW

**Comment by jgphpc** [comment]
@jenkins-cscs retry all

**Comment by jgphpc** [comment]
@jenkins-cscs retry this please

**Comment by twrobinson** [comment]
retest this please

**Comment by twrobinson** [comment]
I guess there are no tests to perform here? Can this be merged?

**Comment by lucamar** [comment]
retest this please

**Pull request merged**
