### PR TITLE
[daint-gpu] Theano

### PR DESCRIPTION
**Pull request by victorusu**
Daint-gpu version of Then 0.9.0

These versions are all GPU based.

### CODE REVIEW

**Comment by gppezzi** [comment]
could you please try to run a basic example from [here](https://user.cscs.ch/scientific_computing/supported_applications/theano/) before merging?

**Comment by victorusu** [comment]
This part works:
```bash
export CRAY_CUDA_MPS=1
salloc -N1 -C gpu
srun python -c 'import theano; theano.test()'
```

This part does not work:
```bash
wget http://deeplearning.net/tutorial/code/convolutional_mlp.py
salloc -N1 -C gpu
export CRAY_CUDA_MPS=1
export THEANO_FLAGS='cuda.root=$CRAY_CUDATOOLKIT_DIR,device=gpu,floatX=float32'
time srun python convolutional_mlp.py
```

The error is:
```bash
Using gpu device 0: Tesla P100-PCIE-16GB (CNMeM is disabled, cuDNN 5105)
Traceback (most recent call last):
  File "convolutional_mlp.py", line 38, in <module>
    from logistic_sgd import LogisticRegression, load_data
ImportError: No module named 'logistic_sgd'
srun: error: nid02086: task 0: Exited with exit code 1
srun: Terminating job step 2084454.0
```

**Comment by victorusu** [comment]
Probably @mschoengens can help with the issue.

**Comment by mschoengens** [comment]
Download the following files and it should work:

wget http://deeplearning.net/tutorial/code/mlp.py
wget http://deeplearning.net/tutorial/code/logistic_sgd.py
wget http://www.iro.umontreal.ca/~lisa/deep/data/mnist/mnist.pkl.gz

**Comment by gppezzi** [comment]
Thanks @victorusu and @mschoengens

**Pull request merged**
