### PR TITLE
Refactored TensorFlow patches such that library paths are dynamically…

### PR DESCRIPTION
**Pull request by mschoengens**
… created depending on which module is loaded.

### CODE REVIEW

**Comment by gppezzi** [comment]
ok to test

**Comment by gppezzi** [comment]
@mschoengens this does not work, as Bazel doesn't seem to accept environment variables here.

I think we need to take a deeper look on how to pass arguments to Bazel if we want to avoid hardcoded paths.

**Comment by mschoengens** [comment]
The environment variables are substituted with the real path by sed (see the patch file)

When I run it in the terminal everything works fine -- can you send me the Jenkins error log?

**Comment by gppezzi** [comment]
Sorry I've missed the sed...

The error was on the multicore version (branch was not in sync with master), so it was unrelated with this PR.

I've synced with master and now it looks good. Thanks @mschoengens

**Pull request merged**
