### PR TITLE
[daint-gpu] latest version of OTF2 library with CrayIntel

### PR DESCRIPTION
**Pull request by toxa81**

### CODE REVIEW

**Comment by toxa81** [comment]
test this please

**Comment by jgphpc** [comment]
before merging, i would add python bindings as in https://github.com/eth-cscs/production/blob/master/easybuild/easyconfigs/o/OTF2/OTF2-2.1-CrayGNU-17.08-python3-bindings.eb

**Comment by toxa81** [comment]
I'm afraid the Python bindings are for GNU program environment. I need CrayIntel.

**Comment by toxa81** [comment]
@jgphpc 
module avail PyExtensions

------------------------------------------------ /apps/daint/UES/jenkins/6.0.UP04/gpu/easybuild/modules/all ------------------------------------------------
PyExtensions/2.7-CrayGNU-17.08          PyExtensions/3.5-CrayGNU-17.08          PyExtensions/3.6-CrayGNU-17.12
PyExtensions/2.7.13.1-CrayGNU-17.08     PyExtensions/3.6-CrayGNU-17.08(default) PyExtensions/3.6.1.1-CrayGNU-17.08

all CrayGNU

**Comment by jgphpc** [comment]
:ok:

**Pull request merged**
