### PR TITLE
[WIP] tool container test

### PR DESCRIPTION
**Pull request by jgphpc**
Fix for [#295](https://jira.cscs.ch/browse/CONTAINER-295)

### CODE REVIEW

**Comment by lucamar** [comment]
@jgphpc Still work in progress?

**Comment by jgphpc** [comment]
@lucamar yes

**Comment by lucamar** [comment]
@jgphpc Still work in progress?

**Comment by jgphpc** [comment]
yes, sorry. I will update this week.

**Comment by jgphpc** [comment]
https://jira.cscs.ch/browse/UES-863

**Pull request closed without merging**
