### PR TITLE
[dom-gpu] VTK for GPU+EGL for 18.08

### PR DESCRIPTION
**Pull request by jfavre**
VTK libs and vtkpython for batch-mode rendering

### CODE REVIEW

**Comment by jfavre** [comment]
COMPLETED: Installation ended successfully
== Results of the build can be found in the log file(s) /scratch/snx1600tds/jfavre/daint/software/VTK/8.1.1-EGL-CrayGNU-18.08/easybuild/easybuild-VTK-8.1.1-EGL-20180828.094018.log

**Comment by gppezzi** [comment]
retest this please

**Comment by gppezzi** [comment]
@kraushm will take care of opening the case with Cray for the missing variable pointing to the python root

**Comment by kraushm** [comment]
CrayPort-ticket opened: case# 220704

Request to restore the LD_LIBRARY_PATH and PYTHON_PATH variable settings as it was done in the previous cray-python/17.06.1 module.

**Pull request merged**
