### PR TITLE
[daint dom kesch leone monch] Easyconfig for ReFrame 2.12

### PR DESCRIPTION
**Pull request by vkarak**
- Also adapted the Python-bare package to include (again) nose.

### CODE REVIEW

**Comment by lucamar** [comment]
Thanks @vkarak: since you update `Python-bare`, I suggest to use the latest available versions of the Python extensions. E.g. for `setuptools`, `pip` and `virtualenv` I have updated links below:
```
    ('setuptools', '39.1.0', {
        'source_urls': ['https://files.pythonhosted.org/packages/a6/5b/'    \
                        'f399fcffb9128d642387133dc3aa9bb81f127b949cd4d9f63e5602ad1d71/'],
        'source_tmpl': '%(name)s-%(version)s.zip',
    }),
    ('pip', '10.0.1', {
        'source_urls': ['https://files.pythonhosted.org/packages/ae/e8/'    \
                        '2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/'],
    }),
    ('virtualenv', '15.2.0', {
        'source_urls': ['https://files.pythonhosted.org/packages/b1/72/'    \
                        '2d70c5a1de409ceb3a27ff2ec007ecdd5cc52239e7c74990e32af57affe9/'],
    }),
```

**Comment by vkarak** [comment]
@lucamar They should be since @teojgo has updated it quite recently (#582). I've just added `nose` again in the list of dependencies.

**Comment by vkarak** [comment]
Ok, I'll update the versions, they seem to have flipped the last two weeks!

**Comment by teojgo** [comment]
The setuptools was updated just 6 days ago.

**Comment by vkarak** [comment]
retest this please

**Pull request merged**
