### PR TITLE
add octave Piz Daint

### PR DESCRIPTION
**Pull request by gppezzi**
@jgphpc  can you please test?

/apps/daint/UES/6.0.UP02/sandbox-haswell/easybuild/

### CODE REVIEW

**Comment by jgphpc** [comment]
* piccinal@daint101:~$ octave --no-gui --no-window-system 
   * octave:1> doc
```
The info file
/apps/daint/UES/6.0.UP02/sandbox-haswell/easybuild/software/
Octave/4.2.0-CrayGNU-2016.11/share/info/octave.info
or compressed versions do not exist
```


* tar tf /apps/common/easybuild/sources/o/Octave/octave-4.2.0.tar.gz |grep octave.info
`octave-4.2.0/doc/liboctave/liboctave.info*`

**Comment by gppezzi** [comment]
@jgphpc the original recipe had 
```
configopts += ' --disable-docs '
````

**Comment by victorusu** [comment]
Using:

```
octave
```

```
__run_test_suite__
```

```
Summary:

  PASS     14569
  FAIL         3
  XFAIL       33
  SKIPPED    312
```

The `FAIL` are serious failures and `XFAIL` are known to fail. 

One error:
Location  |  Observed  |  Expected  |  Reason 
       (2,2)       0.45338      0.45338      Abs err 3.8858e-16 exceeds tol 2.2204e-16

The other two errors:
publish: cannot create output directory. Permission denied
publish: cannot create output directory. Permission denied

**Comment by jgphpc** [comment]
## TODO

### OpenMP test
* ...

### Missing deps :ok:

* configure: WARNING: `Qhull` library not found. This will result in loss of functionality of some geometry functions (convex hull, Delaunay triangulation, Voronoi diagram,...) => _need_ ?

* configure: WARNING: OpenGL libs (GL and GLU) not found.  OpenGL graphics will be disabled. :ok:
* configure: WARNING: OSMesa library not found.  Offscreen rendering with OpenGL will be disabled. :ok:

* sparse
```
configure: WARNING: AMD library not found.  
configure: WARNING: CAMD library not found.  
configure: WARNING: COLAMD library not found.  
etc...
This will result in some lack of functionality for sparse matrices.
```

### cray-libsci vs lm
* ...

**Comment by jgphpc** [comment]
## Running on the login node
* export OMP_NUM_THREADS=1
* /usr/bin/time -p octave-cli --eval  \_\_run_test_suite\_\_ 
   * `107.41 seconds`
   * 16 XFAIL (=known bugs)
   * no FAIL but execution stops inside `profiler/profile.m`
eff_ddt_octave

* but does not fail if i run manually:
* piccinal@daint102:/scratch/snx3000/piccinal/RT/octave$ ./octave-cli 
```
octave:1> test profile.m
warning: function ./profile.m shadows a core library function
PASSES 4 out of 4 tests
```

* piccinal@daint102:/scratch/snx3000/piccinal/RT/octave$ srun -n1 ./octave-cli 
```
test profile.m
warning: function ./profile.m shadows a core library function
PASSES 4 out of 4 tests
```

**Comment by jgphpc** [comment]
@gppezzi 
Is the -fopenmp flag added by Octave's configure or by us ? I can not find it in [.eb](https://github.com/eth-cscs/production/blob/fe3270b8082e50445ee0f15566fd950b72e266af/easybuild/easyconfigs/o/Octave/Octave-4.2.0-CrayGNU-2016.11.eb) ?

**Comment by jgphpc** [comment]
## mappers.cc-tst
* /usr/bin/time -p srun -n1 octave-cli --eval "test 3.tst verbose"
```
>>>>> /scratch/snx3000/piccinal/RT/octave/JG/MAPPERS/3.tst
***** test
 rval = 0;
 ival = 1.31695789692481635;
 obs = acos ([2, 2-i*eps, 2+i*eps]);
 exp = [rval + ival*i, rval + ival*i, rval - ival*i];
 assert (obs, exp, 2*eps);
 rval = pi;
 obs = acos ([-2, -2-i*eps, -2+i*eps]);
 exp = [rval - ival*i, rval + ival*i, rval - ival*i];
 assert (obs, exp, 2*eps);
 assert (acos ([2 0]),  [ival*i, pi/2], 2*eps);
 assert (acos ([2 0i]), [ival*i, pi/2], 2*eps);
***** xtest <45507>
 x = [1, -1, i, -i] .* 1e150;
 v = [0, pi, pi/2, pi/2];
 assert (real (acos (x)), v);
***** error acos ()
***** error acos (1, 2)
PASSES 4 out of 4 tests
```

* CN = real `23.31`
* LN = real `0.42`

**Comment by jgphpc** [comment]
* The problem is in `$LD_LIBRARY_PATH` search path which adds a penalty of 15-30 seconds at startup on the compute node but for jobs longer than 30 sec, the startup penalty will vanish:

```
n=10000;
A=randn(n,n);
b=randn(n,1);
t0=time();
x=A\b;
t1=time(); printf("cscs elapsed time1= %f\n",t1-t0); t0=t1;
```
* /usr/bin/time -p octave-cli ./0.m

### LN
```
cscs elapsed time1= 23.20
real = 26.13
```

### CN
```
cscs elapsed time1= 18.5 <------faster than LN
real = 32.6   <--------- 32-18 = 14sec = startup time
```

**Comment by jgphpc** [comment]
ok to test

**Comment by jgphpc** [comment]
retest this please (wrong .eb ?)

**Comment by jgphpc** [comment]
retest this please (debugging...)

**Comment by jgphpc** [comment]
jenkins => retest this please

**Pull request merged**
