### PR TITLE
[dom]  bsc pe/1708

### PR DESCRIPTION
**Pull request by jgphpc**

### CODE REVIEW

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
`Both GPU and MC builds selected on system dom`
Several dependencies missing, e.g.:
`ERROR: Irresolvable dependencies encountered: libunwind/.1.2.1-CrayGNU-17.08`

**Comment by jgphpc** [comment]
`libunwind/.1.2.1-CrayGNU-17.08` is pushed in https://github.com/eth-cscs/production/pull/285
Is it ok if i add it to this PR too ?

**Comment by jgphpc** [comment]
retest this please

**Comment by jgphpc** [comment]
retest this please

**Comment by jgphpc** [comment]
jenkins failed because x was messing up with dom, retest this please.

**Pull request merged**
