### PR TITLE
WIP [tsa arolla] PGI toolchain on Tsa/Arolla RH7.5

### PR DESCRIPTION
**Pull request by kraushm**
Initial commit containing the main dependencies required for compiling COSMO

### CODE REVIEW

**Comment by lucamar** [comment]
I think that his pull request should be merged in #1200

**Comment by lucamar** [comment]
@kraushm Do you think that we can close this pull request?

**Comment by kraushm** [comment]
retest this please

**Comment by lucamar** [comment]
Closing since the OS is outdated now

**Pull request closed without merging**
