### PR TITLE
[dom daint eiger tsa] Add recipe for ReFrame CSCS tests version 23.10

### PR DESCRIPTION
**Pull request by jenkins-cscs**

### CODE REVIEW

**Comment by lucamar** [comment]
Ok to test

**Comment by lucamar** [comment]
Hi @ekouts and @teojgo, can we merge this pull request?

**Comment by lucamar** [comment]
The build on Eiger failed since the `/apps` file system is mounted on the old read-only scratch there:
```
== FAILED: Installation ended unsuccessfully (build directory: /tmp/jenscscs/990ad22/reframecscstests/23.10/system-system): build failed (first 300 chars): Failed to create directory /apps/common/UES/easybuild/sources/r/reframe: [Errno 30] Read-only file system: '/apps/common/UES/easybuild' (took 1 secs)
```
The source folder on Eiger is now `/capstor/apps/cscs/common/easybuild/sources`.

**Comment by ekouts** [comment]
Should we simply close this one, since #2922 was merged? What do you think @teojgo ?

**Comment by teojgo** [comment]
> Should we simply close this one, since #2922 was merged? What do you think @teojgo ?

Let's close it, I agree.

**Pull request closed without merging**
