### PR TITLE
[dom] Remove python variables in Bazel

### PR DESCRIPTION
**Pull request by ekouts**

### CODE REVIEW

**Comment by ekouts** [comment]
retest this please

**Comment by ekouts** [comment]
retest this please

**Comment by lucamar** [comment]
Should we close this pull request as discussed @ekouts  and @henrique?

**Comment by ekouts** [comment]
I think that we can close it. The python variables will not be updated in the future and there are more recent versions of Bazel in any case.

**Comment by henrique** [comment]
yeah, I think we can close this
thanks @lucamar and @ekouts

**Pull request closed without merging**
