### PR TITLE
[daint,dom] Update production lists with HPX

### PR DESCRIPTION
**Pull request by msimberg**
Also adds HPX 1.3.0 recipes for CrayGNU 18.08. Continuation of #1260.

### CODE REVIEW

**Comment by victorusu** [comment]
@jenkins-cscs test this please

**Comment by msimberg** [comment]
Can the CI be retriggered? I'm guessing nothing ran because I left out the `[daint,dom]` tag when I opened the PR.

**Comment by msimberg** [comment]
retest this please

**Comment by victorusu** [comment]
@jenkins-cscs test this please

**Comment by msimberg** [comment]
Dom failed for the new files but I guess that is to be expected. I wasn't sure if I should add `dom` to the title but did so because I updated the production lists. Or am I missing something?

**Comment by teojgo** [comment]
@msimberg It's fine since the 18.08 recipes are not meant for dom. They build fine on daint. Therefore, it can be merged.

**Pull request merged**
