### PR TITLE
[daint-mc,dom-mc] Add IJulia to jupyterlab-1.2.4 (mc recipe)

### PR DESCRIPTION
**Pull request by omlins**
This work includes a split of the recipe: one recipe for the mc partition and one for the gpu partition.
This PR contains only the MC recipe.

### CODE REVIEW

**Comment by omlins** [comment]
retest this please

**Comment by twrobinson** [comment]
It looks like the "jupyter lab build" failed?

**Comment by omlins** [comment]
Building output on local machine
For GPU
```
omlins@daint106:/scratch/snx3000/omlins/9_soft_install_ijulia/production/easybuild/easyconfigs/j/jupyterlab> eb jupyterlab-1.2.4-CrayGNU-19.10-cuda-10.1-batchspawner.eb -f
== temporary log file in case of crash /run/user/24345/easybuild/tmp/eb-SzTZO2/easybuild-nl8BLe.log
== processing EasyBuild easyconfig /scratch/snx3000/omlins/9_soft_install_ijulia/production/easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.4-CrayGNU-19.10-cuda-10.1-batchspawner.eb
== building and installing jupyterlab/1.2.4-CrayGNU-19.10-cuda-10.1-batchspawner...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== installing extension pyrsistent 0.15.4 (1/84)...
== installing extension attrs 19.1.0 (2/84)...
== installing extension jsonschema 3.0.1 (3/84)...
== installing extension json5 0.8.5 (4/84)...
== installing extension Send2Trash 1.5.0 (5/84)...
== installing extension tornado 6.0.3 (6/84)...
== installing extension pyzmq 18.0.2 (7/84)...
== installing extension python-dateutil 2.8.0 (8/84)...
== installing extension jupyter_core 4.5.0 (9/84)...
== installing extension jupyter_client 5.3.1 (10/84)...
== installing extension MarkupSafe 1.1.1 (11/84)...
== installing extension Jinja2 2.10.1 (12/84)...
== installing extension webencodings 0.5.1 (13/84)...
== installing extension bleach 3.1.0 (14/84)...
== installing extension defusedxml 0.6.0 (15/84)...
== installing extension entrypoints 0.3 (16/84)...
== installing extension mistune 0.8.4 (17/84)...
== installing extension nbformat 4.4.0 (18/84)...
== installing extension pandocfilters 1.4.2 (19/84)...
== installing extension testpath 0.4.2 (20/84)...
== installing extension nbconvert 5.5.0 (21/84)...
== installing extension prometheus_client 0.7.1 (22/84)...
== installing extension terminado 0.8.2 (23/84)...
== installing extension jupyterlab_server 1.0.0 (24/84)...
== installing extension ipykernel 5.1.1 (25/84)...
== installing extension notebook 6.0.0 (26/84)...
== installing extension jupyterlab 1.2.4 (27/84)...
== installing extension SQLAlchemy 1.3.6 (28/84)...
== installing extension Mako 1.0.14 (29/84)...
== installing extension alembic 1.0.11 (30/84)...
== installing extension python-editor 1.0.4 (31/84)...
== installing extension async_generator 1.10 (32/84)...
== installing extension pycparser 2.19 (33/84)...
== installing extension cffi 1.12.3 (34/84)...
== installing extension asn1crypto 0.24.0 (35/84)...
== installing extension cryptography 2.7 (36/84)...
== installing extension pyOpenSSL 19.0.0 (37/84)...
== installing extension certipy 0.1.3 (38/84)...
== installing extension entrypoints 0.3 (39/84)...
== installing extension oauthlib 3.0.2 (40/84)...
== installing extension pamela 1.0.0 (41/84)...
== installing extension urllib3 1.25.3 (42/84)...
== installing extension idna 2.8 (43/84)...
== installing extension chardet 3.0.4 (44/84)...
== installing extension certifi 2019.6.16 (45/84)...
== installing extension requests 2.22.0 (46/84)...
== installing extension jupyterhub 1.0.0 (47/84)...
== installing extension widgetsnbextension 3.5.1 (48/84)...
== installing extension ipywidgets 7.5.1 (49/84)...
== installing extension ipympl 0.3.3 (50/84)...
== installing extension param 1.9.2 (51/84)...
== installing extension pyct 0.4.6 (52/84)...
== installing extension colorcet 2.0.2 (53/84)...
== installing extension zstandard 0.13.0 (54/84)...
== installing extension itk-core 5.0.1 (55/84)...
== installing extension itk-numerics 5.0.1 (56/84)...
== installing extension itk-filtering 5.0.1 (57/84)...
== installing extension itk-meshtopolydata 0.5.1 (58/84)...
== installing extension ipydatawidgets 4.0.1 (59/84)...
== installing extension itkwidgets 0.25.0 (60/84)...
== installing extension retrying 1.3.3 (61/84)...
== installing extension plotly 4.0.0 (62/84)...
== installing extension PyYAML 5.1.2 (63/84)...
== installing extension bokeh 1.3.4 (64/84)...
== installing extension packaging 19.1 (65/84)...
== installing extension Pillow 6.1.0 (66/84)...
== installing extension traittypes 0.2.1 (67/84)...
== installing extension bqplot 0.11.6 (68/84)...
== installing extension psutil 5.6.3 (69/84)...
== installing extension nbresuse 0.3.2 (70/84)...
== installing extension graphviz 0.12 (71/84)...
== installing extension simpervisor 0.3 (72/84)...
== installing extension multidict 4.5.2 (73/84)...
== installing extension yarl 1.3.0 (74/84)...
== installing extension typing_extensions 3.7.4 (75/84)...
== installing extension async-timeout 3.0.1 (76/84)...
== installing extension idna-ssl 1.1.0 (77/84)...
== installing extension aiohttp 3.5.4 (78/84)...
== installing extension jupyter-server-proxy 1.1.0 (79/84)...
== installing extension dask_labextension 1.0.3 (80/84)...
== installing extension pynvml 8.0.4 (81/84)...
== installing extension jupyterlab-nvdashboard 0.1.11 (82/84)...
== installing extension bash_kernel 0.7.2 (83/84)...
== installing extension batchspawner 68a1fcd (84/84)...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 26 min 52 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/omlins/9_soft_install_ijulia/software/jupyterlab/1.2.4-CrayGNU-19.10-cuda-10.1-batchspawner/easybuild/easybuild-jupyterlab-1.2.4-20200205.100516.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /run/user/24345/easybuild/tmp/eb-SzTZO2/easybuild-nl8BLe.log* have been removed.
== Temporary directory /run/user/24345/easybuild/tmp/eb-SzTZO2 has been removed.
omlins@daint106:/scratch/snx3000/omlins/9_soft_install_ijulia/production/easybuild/easyconfigs/j/jupyterlab> 
```

For MC:
```
omlins@daint106:/scratch/snx3000/omlins/9_soft_install_ijulia/production/easybuild/easyconfigs/j/jupyterlab> eb jupyterlab-1.2.4-CrayGNU-19.10-batchspawner.eb -f
== temporary log file in case of crash /run/user/24345/easybuild/tmp/eb-xNdAUo/easybuild-k5EONW.log
== processing EasyBuild easyconfig /scratch/snx3000/omlins/9_soft_install_ijulia/production/easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.4-CrayGNU-19.10-batchspawner.eb
== building and installing jupyterlab/1.2.4-CrayGNU-19.10-batchspawner...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== installing extension pyrsistent 0.15.4 (1/84)...
== installing extension attrs 19.1.0 (2/84)...
== installing extension jsonschema 3.0.1 (3/84)...
== installing extension json5 0.8.5 (4/84)...
== installing extension Send2Trash 1.5.0 (5/84)...
== installing extension tornado 6.0.3 (6/84)...
== installing extension pyzmq 18.0.2 (7/84)...
== installing extension python-dateutil 2.8.0 (8/84)...
== installing extension jupyter_core 4.5.0 (9/84)...
== installing extension jupyter_client 5.3.1 (10/84)...
== installing extension MarkupSafe 1.1.1 (11/84)...
== installing extension Jinja2 2.10.1 (12/84)...
== installing extension webencodings 0.5.1 (13/84)...
== installing extension bleach 3.1.0 (14/84)...
== installing extension defusedxml 0.6.0 (15/84)...
== installing extension entrypoints 0.3 (16/84)...
== installing extension mistune 0.8.4 (17/84)...
== installing extension nbformat 4.4.0 (18/84)...
== installing extension pandocfilters 1.4.2 (19/84)...
== installing extension testpath 0.4.2 (20/84)...
== installing extension nbconvert 5.5.0 (21/84)...
== installing extension prometheus_client 0.7.1 (22/84)...
== installing extension terminado 0.8.2 (23/84)...
== installing extension jupyterlab_server 1.0.0 (24/84)...
== installing extension ipykernel 5.1.1 (25/84)...
== installing extension notebook 6.0.0 (26/84)...
== installing extension jupyterlab 1.2.4 (27/84)...
== installing extension SQLAlchemy 1.3.6 (28/84)...
== installing extension Mako 1.0.14 (29/84)...
== installing extension alembic 1.0.11 (30/84)...
== installing extension python-editor 1.0.4 (31/84)...
== installing extension async_generator 1.10 (32/84)...
== installing extension pycparser 2.19 (33/84)...
== installing extension cffi 1.12.3 (34/84)...
== installing extension asn1crypto 0.24.0 (35/84)...
== installing extension cryptography 2.7 (36/84)...
== installing extension pyOpenSSL 19.0.0 (37/84)...
== installing extension certipy 0.1.3 (38/84)...
== installing extension entrypoints 0.3 (39/84)...
== installing extension oauthlib 3.0.2 (40/84)...
== installing extension pamela 1.0.0 (41/84)...
== installing extension urllib3 1.25.3 (42/84)...
== installing extension idna 2.8 (43/84)...
== installing extension chardet 3.0.4 (44/84)...
== installing extension certifi 2019.6.16 (45/84)...
== installing extension requests 2.22.0 (46/84)...
== installing extension jupyterhub 1.0.0 (47/84)...
== installing extension widgetsnbextension 3.5.1 (48/84)...
== installing extension ipywidgets 7.5.1 (49/84)...
== installing extension ipympl 0.3.3 (50/84)...
== installing extension param 1.9.2 (51/84)...
== installing extension pyct 0.4.6 (52/84)...
== installing extension colorcet 2.0.2 (53/84)...
== installing extension zstandard 0.13.0 (54/84)...
== installing extension itk-core 5.0.1 (55/84)...
== installing extension itk-numerics 5.0.1 (56/84)...
== installing extension itk-filtering 5.0.1 (57/84)...
== installing extension itk-meshtopolydata 0.5.1 (58/84)...
== installing extension ipydatawidgets 4.0.1 (59/84)...
== installing extension itkwidgets 0.25.0 (60/84)...
== installing extension retrying 1.3.3 (61/84)...
== installing extension plotly 4.0.0 (62/84)...
== installing extension PyYAML 5.1.2 (63/84)...
== installing extension bokeh 1.3.4 (64/84)...
== installing extension packaging 19.1 (65/84)...
== installing extension Pillow 6.1.0 (66/84)...
== installing extension traittypes 0.2.1 (67/84)...
== installing extension bqplot 0.11.6 (68/84)...
== installing extension psutil 5.6.3 (69/84)...
== installing extension nbresuse 0.3.2 (70/84)...
== installing extension graphviz 0.12 (71/84)...
== installing extension simpervisor 0.3 (72/84)...
== installing extension multidict 4.5.2 (73/84)...
== installing extension yarl 1.3.0 (74/84)...
== installing extension typing_extensions 3.7.4 (75/84)...
== installing extension async-timeout 3.0.1 (76/84)...
== installing extension idna-ssl 1.1.0 (77/84)...
== installing extension aiohttp 3.5.4 (78/84)...
== installing extension jupyter-server-proxy 1.1.0 (79/84)...
== installing extension dask_labextension 1.0.3 (80/84)...
== installing extension pynvml 8.0.4 (81/84)...
== installing extension jupyterlab-nvdashboard 0.1.11 (82/84)...
== installing extension bash_kernel 0.7.2 (83/84)...
== installing extension batchspawner 68a1fcd (84/84)...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 28 min 1 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/omlins/9_soft_install_ijulia/software/jupyterlab/1.2.4-CrayGNU-19.10-batchspawner/easybuild/easybuild-jupyterlab-1.2.4-20200205.100624.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /run/user/24345/easybuild/tmp/eb-xNdAUo/easybuild-k5EONW.log* have been removed.
== Temporary directory /run/user/24345/easybuild/tmp/eb-xNdAUo has been removed.
omlins@daint106:/scratch/snx3000/omlins/9_soft_install_ijulia/production/easybuild/easyconfigs/j/jupyterlab> 
```

**Comment by omlins** [comment]
The jupyterlab modules seem to be built correctly, but somehow they are not loaded correctly when launching jupyterhub.

**Comment by omlins** [comment]
retest this please

**Comment by twrobinson** [comment]
retest this please

**Pull request merged**
