### PR TITLE
Cp2k

### PR DESCRIPTION
**Pull request by lucamar**
perftools-lite/6.4.3 produces an instrumented executable that gives a report on the multicore portion of the system only (report on the gpu portion of the system is work in progress, see Cray bug #845303/case #150425 - perftools6.4.2 Segmentation fault)

### CODE REVIEW

**Comment by gppezzi** [comment]
retest this please

**Comment by jgphpc** [comment]
retest this please

**Comment by jgphpc** [comment]
retest this please  (changed git diff line)

**Comment by jgphpc** [comment]
retest this please

**Comment by gppezzi** [comment]
retest this please

**Comment by jgphpc** [comment]
retest this please

**Comment by jgphpc** [comment]
retest this please

**Pull request merged**
