### PR TITLE
[dom-mc] Update NAMD_mc to TC 19.03

### PR DESCRIPTION
**Pull request by ChristopherBignamini**

### CODE REVIEW

**Comment by lucamar** [comment]
@ChristopherBignamini There is already pull request #1050 open for this recipe (please use `[dom-gpu]` or `[dom-mc]` only in the title of the pull request if you don't need both, since `[dom]` will build on both of them and it will take more time)

**Comment by vkarak** [comment]
@ChristopherBignamini Isn't this a duplicate of #1050 ?

**Comment by ChristopherBignamini** [comment]
@lucamar @vkarak yes, it can be deleted. The NAMD easyconfig in #1050 is identical to the one of this PR and should work.

**Comment by vkarak** [comment]
@lucamar I am closing this PR then.

**Pull request closed without merging**
