### PR TITLE
[dom-gpu] Add pytorch 1.7.1 cdt/20.11

### PR DESCRIPTION
**Pull request by henrique**

### CODE REVIEW

**Comment by henrique** [comment]
retest this please

**Comment by lucamar** [comment]
@henrique The failure is due to the lack of dependencies on the system: please keep the pull request on hold until we merge #2112 and #2113
```
ERROR: Missing dependencies: CrayGNU/.20.11, Boost/1.70.0-CrayGNU-20.11 (no easyconfig file or existing module found)
```

**Comment by henrique** [comment]
retest this please

**Comment by henrique** [comment]
> @henrique The failure is due to the lack of dependencies on the system: please keep the pull request on hold until we merge #2112 and #2113

Thanks @lucamar all checks passed today
(now rebased and added to prod file)

**Review by rsarm — APPROVED** [review]

**Pull request merged**
