### PR TITLE
Adding support for python3 in boost for cray

### PR DESCRIPTION
**Pull request by victorusu**
* Modified the boost easyblock on cray in order to add support to python3.
* Added Boost 1.62.0 and Python 3.5.2 easyconfig

The easyblock was also tested using Python 2.7.12 in order to check whether python2 was broken.

The log files and modules can be accessed on daint using:

```
module use $SCRATCH/bin/modules/all
module load Boost/1.62.0-CrayGNU-2016.11-Python-2.7.12 
or 
module load Boost/1.62.0-CrayGNU-2016.11-Python-3.5.2
```
**Note:** The `$SCRATCH` should point to my scratch on daint.

### CODE REVIEW

**Comment by gppezzi** [comment]
ok to test

**Comment by gppezzi** [comment]
test this please

**Comment by victorusu** [comment]
test this please

**Comment by gppezzi** [comment]
retest this please

**Pull request merged**
