### PR TITLE
[daint-gpu] IPython-6.1.0 in CrayGNU2016.11 for Python-3.5.2

### PR DESCRIPTION
**Pull request by teojgo**
libsodium is used inside the IPython package

### CODE REVIEW

**Comment by teojgo** [comment]
test this please

**Comment by teojgo** [comment]
retest this please

**Comment by teojgo** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
@teojgo please pull master branch changes in your branch, since it is not in sync:
```
Current diff list by 'git diff origin/master..HEAD --name-only --oneline --no-merges --diff-filter=ACMRTUXB':
easybuild/cray_external_modules_metadata.cfg
easybuild/easyconfigs/i/IPython/IPython-6.1.0-CrayGNU-2016.11-Python-3.5.2.eb
easybuild/easyconfigs/l/libsodium/libsodium-1.0.13-CrayGNU-2016.11.eb
easybuild/easyconfigs/o/OTF2/OTF2-2.0.eb
easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-CrayGNU-2016.11.eb
easybuild/easyconfigs/p/PyZMQ/PyZMQ-17.0.0b1-CrayGNU-2016.11-Python-3.5.2-zmq4.eb
easybuild/easyconfigs/u/util-linux/util-linux-2.27.1-CrayGNU-2016.11.eb
easybuild/easyconfigs/v/Vim/Vim-8.0.eb
easybuild/easyconfigs/v/Visit/Visit-2.12.0-CrayGNU-2016.11.eb
easybuild/easyconfigs/v/vampir/vampir-9.3.0.eb
easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.2.2-CrayGNU-2016.11.eb
jenkins-builds/6.0.UP02-2016.11-gpu
jenkins-builds/6.0.UP02-2016.11-mc
jenkins-builds/6.0.UP04-17.08-gpu
jenkins-builds/6.0.UP04-17.08-mc
jenkins-builds/MCH-RH7.3-17.02
jenkins-builds/common-RH6.7-2016.10
jenkins-builds/common-SLES12-2016.10
jenkins-builds/leone-RHEL6.7EUS-17.06
jenkins-builds/monch-RH6.9-17.06
```

**Comment by teojgo** [comment]
retest this please

**Pull request merged**
