### PR TITLE
[daint dom eiger pilatus] ddt/22.1.3

### PR DESCRIPTION
**Pull request by jgphpc**

### CODE REVIEW

**Comment by jgphpc** [comment]
@jenkins-cscs retry this please

**Comment by jgphpc** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Review by lucamar — APPROVED** [review]
Thanks @jgphpc: plede note that the changes will be deployed on EIger and Piz Daint as well, since Dom and Pilatus are kept in sync with the production systems

**Pull request merged**
