### PR TITLE
[daint, dom] ELPA library 

### PR DESCRIPTION
**Pull request by toxa81**
ELPA eb script

### CODE REVIEW

**Comment by toxa81** [comment]
it works in my local environment on Daint

**Comment by toxa81** [comment]
strange, I can build it on Dom:
[antonk@dom101 tmp]$ module load EasyBuild-custom/cscs
[antonk@dom101 tmp]$ eb ELPA-2017.11.001-CrayIntel-17.08.eb -r
== temporary log file in case of crash /dev/shm/antonk/easybuild/stage/tmp/eb-xtGgjE/easybuild-b1650A.log
== resolving dependencies ...
== processing EasyBuild easyconfig /users/antonk/tmp/ELPA-2017.11.001-CrayIntel-17.08.eb
== building and installing ELPA/2017.11.001-CrayIntel-17.08...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file(s) /users/antonk/easybuild/dom/haswell/software/ELPA/2017.11.001-CrayIntel-17.08/easybuild/easybuild-ELPA-2017.11.001-20180502.143009.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /dev/shm/antonk/easybuild/stage/tmp/eb-xtGgjE/easybuild-b1650A.log* have been removed.
== Temporary directory /dev/shm/antonk/easybuild/stage/tmp/eb-xtGgjE has been removed.

**Comment by lucamar** [comment]
I am actually building on `dom101`, this is my log file:
```
/dev/shm/lucamar/easybuild/stage/tmp/eb-LoWwyY/easybuild-ELPA-2017.11.001-20180502.142427.JlfDR.log
```

**Comment by toxa81** [comment]
retest this please

**Comment by toxa81** [comment]
looks like a Jenkins issue.. I will try to build on daint

**Comment by toxa81** [comment]
retest this please

**Comment by lucamar** [comment]
@toxa81 I have tried to build again `ELPA` on `dom101` and I still get an error (`compilation aborted for test/C/test.c`:
```
test/C/test.c(190): error: expected an expression
     elpa_set(handle, "na", na, &error);
     ^
```
The log file is `/dev/shm/lucamar/easybuild/stage/tmp/eb-UMyhrf/easybuild-ELPA-2017.11.001-20180517.165910.mgqLJ.log`

**Comment by victorusu** [comment]
@toxa81 and @lucamar me too. Just got the error too!

**Comment by lucamar** [comment]
@toxa81 I have added `&&` at the end of the `preconfigopts` lines. Now I get an error already at the step `configure`:
```
configure: error: No usable BLACS found. If installed in a non-standard place, please specify suitable LDFLAGS and FCFLAGS as arguments to configure
```
Do you think one needs to define the variable `SCALAPACK_LDFLAGS` as well? E.g.: 
```
SCALAPACK_LDFLAGS=-L$MKLROOT/lib/intel64 -lmkl_scalapack_lp64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_lp64
```
By the way, I see that in `LIBS` you use `lmkl_intel_thread` instead of `lmkl_sequential`.

**Comment by toxa81** [comment]
retest this please

**Comment by toxa81** [comment]
retest this please

**Comment by toxa81** [comment]
I don't understand this... I can build it starting from a clean login on Daint:
module unload PrgEnv-cray
module unload cray-libsci
module load PrgEnv-intel
module load gcc/5.3.0
CC=cc FC=ftn CPP=cpp FCPP=cpp LIBS="-L$MKLROOT/lib/intel64 -lmkl_scalapack_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmpi_lp64  -lpthread -lstdc++ -ldl" FCFLAGS="-qopenmp -O3 -xAVX2" CFLAGS="-qopenmp -O3 -xAVX2" ./configure --enable-openmp --enable-static

**Comment by gppezzi** [comment]
By default, our CrayIntel toolchain uses libsci (just unloading cray-libsci it is not enough, see all the exports in the eb log file). 

We could hack our way around if this is a one-off, but we would need to create a new CrayIntel MKL based toolchain for properly doing this build.
 
The problem can also be due to other differences between EB defaults and a clean shell (static vs dynamic for example).

**Comment by toxa81** [comment]
OK! Here is the problem: Intel compiler requires reasonably fresh GCC. The default gcc on the system is 4.8.5 which is a fossil this days. Suggestion: CrayIntel environment should load gcc/5.3.0

**Comment by gppezzi** [comment]
@toxa81 how about [CrayIntel-17.08-mkl.eb](https://gist.github.com/gppezzi/5fd89cdde0e68996adf60c9ca5dc8fca)

Still EB exports many variables (CFLAGS, FFLAGS, ..)  for using libsci so this is only a workaround.

**Comment by lucamar** [comment]
I'm definitely in favour of creating a new toolchain using only `MKL`, which would make Intel builds much simpler.

**Pull request merged**
