### PR TITLE
[WIP] [daint-gpu] jupyterlab 1.2.16 with julia 1.5.0 (PE 20.08)

### PR DESCRIPTION
**Pull request by omlins**

### CODE REVIEW

**Comment by omlins** [comment]
this is just to fix the comment as well.

**Comment by omlins** [comment]
We should probably not do a rebuild on Daint at the moment... I marked it as WIP therefore.

**Comment by twrobinson** [comment]
Is this really necessary?

**Review by twrobinson — COMMENTED** [review]
Is this really necessary?

**Comment by omlins** [comment]
> Is this really necessary?

No problem, we can leave it for this and just undo the removal of hvictor in the other recipe. I was just trying to clean up everything. I will just close this one.

**Pull request closed without merging**
