### PR TITLE
[daint eiger tsa] Add recipe for ReFrame CSCS tests version 22.10

### PR DESCRIPTION
**Pull request by jenkins-cscs**

### CODE REVIEW

**Comment by lucamar** [comment]
Ok to test

**Comment by lucamar** [comment]
The failure on Eiger is expected due to the hostname change of the login nodes, therefore we can ignore it and merge.

**Review by ekouts — APPROVED** [review]

**Comment by teojgo** [comment]
@jenkins-cscs retry all

**Comment by lucamar** [comment]
retest this please

**Pull request merged**
