### PR TITLE
[daint dom eiger pilatus tsa] Add recipe for ReFrame version 3.9.0

### PR DESCRIPTION
**Pull request by jenkins-cscs**

### CODE REVIEW

**Comment by teojgo** [comment]
Ok to test

**Review by teojgo — APPROVED** [review]

**Comment by teojgo** [comment]
retest this please

**Comment by vkarak** [comment]
@teojgo Should we wait until Dom is back, or do we merge anyways?

**Review by vkarak — APPROVED** [review]

**Comment by teojgo** [comment]
retest this please

**Comment by teojgo** [comment]
@vkarak let me retry it

**Pull request merged**
