### PR TITLE
[dom] scalasca pe/1708

### PR DESCRIPTION
**Pull request by jgphpc**

### CODE REVIEW

**Comment by jgphpc** [comment]
These deps are used only by performance tools:
```
 +    ('Cube',        '4.3.5'),
 +    ('OPARI2',      '2.0.2', '', True),
 +    ('OTF2',        '2.0', '', True),
 +    ('SIONlib',     '1.7.1'),
 +    ('PDT',         '3.24', '', True),
```

* This dep fails to build with cce/pgi:
```
 +    ('libunwind',   '1.2.1', '', True),
```

**Comment by lucamar** [comment]
retest this please

**Comment by jgphpc** [comment]
https://jenkins.cscs.ch/job/TestingEB/label=dom/475/console
=> merge please

**Comment by jgphpc** [comment]
> Is it possible to make the build of Scalasca work on compute nodes as well?
In an ideal world with infinite amount of time and space, i would be happy to spend all my time building and rebuilding it. I do not know why jenkins is not setup to run on the compute nodes but i would really appreciate to merge this one and move on.

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
I'm asking since `RegressionEB` runs on the compute nodes and all `Scalasca` builds currently fail on Piz Daint with the following error: 
```
ERROR: Build of /users/jenscscs/production/easybuild/easyconfigs/s/Scalasca/Scalasca-2.3.1-CrayGNU-2016.11.eb failed (err: 'build failed (first 300 chars): Multiple library subdirectories found for PAPI in /opt/cray/pe/papi/5.5.0.1: lib, lib64')
```
See https://jenkins.cscs.ch/view/RegressionEB/job/RegressionEB/label=daint/25/consoleFull

**Comment by lucamar** [comment]
The test completed successfully, only `VisIt` failed but it's not related to this pull request.

**Pull request merged**
