### PR TITLE
[daint, dom] spack-config: cleanup old versions

### PR DESCRIPTION
**Pull request by albestro**
~This new version of spack-config should fix a problem with a deprecated semantic for config files.~

~In particular, 1.7 was using a custom (and not updated anymore) spack version, that was generating config files with "target: any", which is not valid anymore.~

Actually, it was a regression https://github.com/spack/spack/issues/36628. For this reason I would take the chance, instead of updating, to just cleanup older versions of `spack-config`.

### CODE REVIEW

**Review by lucamar — COMMENTED** [review]
Thaks @albestro, do you still need former versions 1.5 1.6 and 1.7 in the build list? If we remove them, the modules won't be removed from the system anyway

**Comment by albestro** [comment]
> Thaks @albestro, do you still need former versions 1.5 1.6 and 1.7 in the build list? If we remove them, the modules won't be removed from the system anyway

I'm ok removing them 😉 AFAIK users should just use the default one, because it fixes previous problems (in general).

**Comment by lucamar** [comment]
Ok to test

**Review by lucamar — APPROVED** [review]
Thanks @albestro

**Pull request merged**
