### PR TITLE
[daint] ABCpy version 0.5

### PR DESCRIPTION
**Pull request by mschoengens**
Newest version of ABCpy.

### CODE REVIEW

**Comment by mschoengens** [comment]
retest please

**Comment by lucamar** [comment]
Thanks @mschoengens , the test on `Piz Daint` was successful, while the test on `Dom` did not run due to some temporary issues with the Jenkins interface:
```
Cannot contact dom: java.io.IOException: remote file operation failed: /scratch/snx3000tds/jenscscs/dom/workspace/TestingEB at hudson.remoting.Channel@439e5163:dom: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on dom failed. The channel is closing down or has closed down
```
I will retest again to make sure that the build succeeds on `Dom` as well.

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
`Dom` is under maintenance, therefore we will not be able to test the build there.

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Pull request merged**
