### PR TITLE
[dom] COSMO-POMPA 24d1ac6 for PE 20.08

### PR DESCRIPTION
**Pull request by omlins**

### CODE REVIEW

**Comment by omlins** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Comment by omlins** [comment]
retest this please

**Comment by omlins** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
The test failed with the following error message:
```
ERROR: Failed to process easyconfig /scratch/snx3000tds/jenscscs/dom/workspace/TestingEB/easybuild/easyconfigs/c/COSMO_pompa/COSMO_pompa-24d1ac6-CrayCCE-20.08-04.09.20-crclim-double-cuda.eb: 
Failed to process easyconfig /scratch/snx3000tds/jenscscs/dom/workspace/TestingEB/easybuild/easyconfigs/c/CrayCCE/CrayCCE-20.08.eb: 
Module command '/opt/cray/pe/modules/3.2.11.4/bin/modulecmd python show cdt.deprecated' failed with exit code 1
```

**Comment by victorusu** [comment]
@omlins, are we still deploying recipes using 20.08?
Does this PR still makes sense?

**Comment by omlins** [comment]
For know we don't have COSMO working with 21.05. So I would wait with removing old PRs.

**Pull request closed without merging**
