### PR TITLE
[daint] Add Boost 1.75.0 with CrayGNU 20.08

### PR DESCRIPTION
**Pull request by aurianer**
Recipe for Boost 1.75.0 on Daint with Cray Programming Environment 20.08 both GNU and Intel (required for HPX CI). Built and tested locally.

### CODE REVIEW

**Comment by teojgo** [comment]
Ok to test

**Review by victorusu — APPROVED** [review]
`lgtm`

**Comment by aurianer** [comment]
Sorry just added a recipe for CrayIntel too, I figured I also needed it. Thanks for reviewing @victorusu!

**Review by victorusu — APPROVED** [review]
Still `lgtm`

**Comment by aurianer** [comment]
I'm not sure what happened in the jenkins run: [srun: Force Terminated job 29646155](https://jenkins.cscs.ch/job/TestingEB/4686/console) for the CrayIntel recipe on daint-mc, looks like it completed for daint-gpu.
Anyone could help me with this? :)

**Comment by lucamar** [comment]
> I'm not sure what happened in the jenkins run: [srun: Force Terminated job 29646155](https://jenkins.cscs.ch/job/TestingEB/4686/console) for the CrayIntel recipe on daint-mc, looks like it completed for daint-gpu.
> Anyone could help me with this? :)

We have sometimes reported issues with the Intel compiler in the Jenkins CI: the compilation hangs  during the configure step, it happened both on compute and login nodes. Let's merge the recipes to see if the issue occurs in `ProductionEB`.

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
I have re-triggered the CI since the issue with the Intel compiler should have been solved now by the system administrators.

**Comment by aurianer** [comment]
Thanks a lot @lucamar!

**Pull request merged**
