### PR TITLE
[daint-gpu] Fix GROMACS 2018.6 PLUMED-2.5.1 recipe

### PR DESCRIPTION
**Pull request by victorusu**

### CODE REVIEW

**Comment by vkarak** [comment]
@victorusu There are a couple of warnings issued during building. Are we fine with them?

**Comment by victorusu** [comment]
@vkarak, the warnings are related to Jenkins itself and the Haswell build for intel compilers on EB.

**Comment by victorusu** [comment]
I will make a PR on EB to hide that warning for Cray

**Comment by vkarak** [comment]
@kraushm Can you also approve?

**Comment by gppezzi** [comment]
IMO the  versionless `[cudatoolkit]` entry in the metadata file should not be kept, as it does not ensure reproducibility as we change the system defaults. 

I'll fix that in #1427, unless you have a reason for keeping it?

**Comment by vkarak** [comment]
Yep, it is not needed. I merged this as is, because otherwise we had to wait for #1427.

**Pull request merged**
