### PR TITLE
[daint-gpu] update ADIOS for daint

### PR DESCRIPTION
**Pull request by jfavre**
== COMPLETED: Installation ended successfully (took 4 mins 52 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/adios/2.9.1-CrayGNU-21.09/easybuild/easybuild-adios-2.9.1-20230921.182600.log
== Build succeeded for 1 out of 1

this update will be needed by ParaView 5.11.2

### CODE REVIEW

**Comment by lucamar** [comment]
Hi @jfavre, the build failed on `daint-gpu` (but not on `daiint-mc`) with the following error:
```
== FAILED: Installation ended unsuccessfully (build directory: /tmp/jenscscs/ec010f2gpu/CMake/3.26.5/system-system): build failed (first 300 chars): Couldn't find file cmake-3.26.5.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /scratch/snx3000/jenscscs/daint101/workspace/TestingEB/easybuild/easyconfigs/c/CMake/c/CMake/cmake-3.26.5.tar.gz, /scratch/snx3000/jenscscs/daint101/workspace/TestingEB/easybuild/eas (took 8 secs)
```
The error might have been caused by a temporary failure to download the tarball. I assume that `CMake/3.22.1` provided on the system does not satisfy the requirements of this build, therefore you need a more recent version: why not the latest Release (3.27.6)?

**Comment by jfavre** [comment]
> Hi @jfavre, the build failed on `daint-gpu` (but not on `daint-mc`) with the following error:
> 
> ```
> == FAILED: Installation ended unsuccessfully (build directory: /tmp/jenscscs/ec010f2gpu/CMake/3.26.5/system-system): build failed (first 300 chars): Couldn't find file cmake-3.26.5.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /scratch/snx3000/jenscscs/daint101/workspace/TestingEB/easybuild/easyconfigs/c/CMake/c/CMake/cmake-3.26.5.tar.gz, /scratch/snx3000/jenscscs/daint101/workspace/TestingEB/easybuild/eas (took 8 secs)
> ```
> 
> The error might have been caused by a temporary failure to download the tarball. I assume that `CMake/3.22.1` provided on the system does not satisfy the requirements of this build, therefore you need a more recent version: why not the latest release (3.27.6)?

this most likely is a temporary failure. Indeed, the compilation of Catalyst requires cmake v3.26 at the minimum. Thus, I selected the highest sub-version number of the 3.26 series.

**Comment by jfavre** [comment]
retest this please

**Review by lucamar — APPROVED** [review]
Thanks @jfavre

**Comment by lucamar** [comment]
retest this please

**Pull request merged**
