### PR TITLE
[dom-gpu] Add emacs 26.1.

### PR DESCRIPTION
**Pull request by mschoengens**
Newer version of emacs so that more models plugins work.

### CODE REVIEW

**Comment by lucamar** [comment]
Thanks @mschoengens: do you specifically need this version? The version installed is the following:  
```
dom101:~$ emacs --version
GNU Emacs 24.3.1
```

**Comment by mschoengens** [comment]
Well, I need a newer version that the installed one, otherwise the spacemacs extensions do not work. I am pushing this since others might be interested as well.

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
@mschoengens: if you check the `Jenkins` logs you will see that the build has completed succesfully on `Dom`: `Piz Daint` is currently under maintenance, therefore the build will never complete, so I'm going to stop the process. Please note that even if the recipe will be merged in the repository, the module will not be built in production.

**Comment by lucamar** [comment]
retest this please

**Comment by mschoengens** [comment]
> Please note that even if the recipe will be merged in the repository, the module will not be built in production.
I think that is fine.

**Pull request merged**
