### PR TITLE
[dom-gpu] QuantumESPRESSO 6.6a2 with CUDA 11

### PR DESCRIPTION
**Pull request by lucamar**
Recipe of QuantumESPRESSO 6.6a2 adapted for CUDA 11 with Cray PE 20.10 on Dom.

### CODE REVIEW

**Comment by lucamar** [comment]
The build succeeds on the login node of Dom, therefore I think that the issue is due to the environment on the compute nodes where `TestingEB` is executed:
```
eb QuantumESPRESSO-6.6a2-CrayPGI-20.10-cuda.eb
[...]
== COMPLETED: Installation ended successfully (took 4 min 35 sec)
== Results of the build can be found in the log file(s) /apps/dom/UES/sandbox/lucamar/easybuild/software/QuantumESPRESSO/6.6a2-CrayPGI-20.10-cuda/easybuild/easybuild-QuantumESPRESSO-6.6a2-20210114.103153.log
== Build succeeded for 1 out of 1
```

**Comment by lucamar** [comment]
I have also managed to build the recipe on the GPU compute nodes `nid00042` and `nid00043` of Dom:
```
srun -A csstaff -C gpu --pty /bin/bash -l
nid00042:~$ eb QuantumESPRESSO-6.6a2-CrayPGI-20.10-cuda.eb --installpath=$EASYBUILD_PREFIX -f
== temporary log file in case of crash /tmp/lucamar/tmp/eb-9PGAWn/easybuild-M80i8s.log
== processing EasyBuild easyconfig /users/lucamar/GitHub/lucamar/production/easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6a2-CrayPGI-20.10-cuda.eb
[...]
== COMPLETED: Installation ended successfully (took 7 min 28 sec)
== Results of the build can be found in the log file(s) /scratch/snx2000tds/lucamar/easybuild/software/QuantumESPRESSO/6.6a2-CrayPGI-20.10-cuda/easybuild/easybuild-QuantumESPRESSO-6.6a2-20210114.104712.log
== Build succeeded for 1 out of 1
```

```
$ srun -u -A csstaff -C gpu eb QuantumESPRESSO-6.6a2-CrayPGI-20.10-cuda.eb --installpath=$EASYBUILD_PREFIX --ignore-locks -f
srun: job 1270333 queued and waiting for resources
srun: job 1270333 has been allocated resources
== temporary log file in case of crash /tmp/lucamar/tmp/eb-X9IK_t/easybuild-uPVYNO.log
== processing EasyBuild easyconfig /users/lucamar/GitHub/lucamar/production/easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6a2-CrayPGI-20.10-cuda.eb
[...]
== COMPLETED: Installation ended successfully (took 7 min 18 sec)
== Results of the build can be found in the log file(s) /scratch/snx2000tds/lucamar/easybuild/software/QuantumESPRESSO/6.6a2-CrayPGI-20.10-cuda/easybuild/easybuild-QuantumESPRESSO-6.6a2-20210114.105611.log
== Build succeeded for 1 out of 1
```

**Comment by lucamar** [comment]
retest this please

**Review by teojgo — APPROVED** [review]

**Comment by lucamar** [comment]
The last `TestingEB` job that failed used the same node `nid00043` that I tested successfully:
```
sacct -j 1270336
     User    Account    JobName        JobID  Partition        NodeList   NNodes   NTasks  AllocCPUS    Elapsed      State ExitCode               Start                 End 
--------- ---------- ---------- ------------ ---------- --------------- -------- -------- ---------- ---------- ---------- -------- ------------------- ------------------- 
 jenscscs   jenscscs  TestingEB 1270336          cscsci        nid00043        1                  24   00:06:51     FAILED      1:0            11:10:18            11:17:09
 ```
I could not reproduce the issue even after logging in as user `jenscscs` with the `cscsci` partition on `nid00043`:
```
srun -u -A jenscscs -p cscsci -C gpu eb QuantumESPRESSO-6.6a2-CrayPGI-20.10-cuda.eb -f
srun: job 1270336 queued and waiting for resources
srun: job 1270336 has been allocated resources
== temporary log file in case of crash /scratch/snx2000tds/jenscscs/easybuild/tmp/eb-qUy2bO/easybuild-V3HeLo.log
== processing EasyBuild easyconfig /users/lucamar/GitHub/lucamar/production/easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6a2-CrayPGI-20.10-cuda.eb
[...]
== COMPLETED: Installation ended successfully (took 11 min 17 sec)
== Results of the build can be found in the log file(s) /scratch/snx2000tds/jenscscs/easybuild/software/QuantumESPRESSO/6.6a2-CrayPGI-20.10-cuda/easybuild/easybuild-QuantumESPRESSO-6.6a2-20210114.122725.log
== Build succeeded for 1 out of 1
```

**Comment by lucamar** [comment]
The error was the following one:
```
/usr/bin/ld: warning: libgfortran.so.5, needed by /opt/cray/pe/hdf5/1.12.0.0/GNU/8.2/lib/libhdf5hl_fortran.so, not found (try using 
-rpath or -rpath-link)
```
It happens also in `ProductionEB`: https://jenkins.cscs.ch/blue/organizations/jenkins/ProductionEB/detail/ProductionEB/1571/pipeline/35

**Pull request merged**
