### PR TITLE
pyfr 1.5.0

### PR DESCRIPTION
**Pull request by gppezzi**
@jgphpc can you please try this out?

### CODE REVIEW

**Comment by jgphpc** [comment]
* Help!
```
Step 1: From your project repository, bring in the changes and test.

git fetch origin
git checkout -b pyfr origin/pyfr
git merge master

Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff pyfr
git push origin master
```

**Comment by jgphpc** [comment]
* https://jenkins.cscs.ch/view/ProductionEB/job/ProductionEBtestingPR-gpu/50/label=daint103/console
   * Mako/1.0.4-CrayGNU-2016.11-Python-3.5.2 :ok:
   * PyFR-1.5.0-CrayGNU-2016.11-Python-3.5.2.eb :ok:

**Comment by gppezzi** [comment]
test this please

**Comment by gppezzi** [comment]
test this please

**Comment by gppezzi** [comment]
test this please

**Pull request merged**
