### PR TITLE
[eiger] Amber

### PR DESCRIPTION
**Pull request by lucamar**
Tentative recipe of Amber with ` cpeGNU` on Eiger.

### CODE REVIEW

**Review by victorusu — APPROVED** [review]
`LGTM`. @lucamar are we testing the performance of this Amber version compared to the AMD Optimized compiler? Because Amber runs much better with intel compared to GNU. This might be the case for the AOCC compiler too.

**Comment by lucamar** [comment]
Thanks for your comment @victorusu, I think that it is a good idea to build and test with `AOCC`. For the moment though, the GNU build is failing with the following error:
```
[ANTECHAMBER]  CC antechamber
/usr/bin/ld: /scratch/e1000/jenscscs/TestingEB/eiger/9aee7ac-4444/software/Amber/20-3-0-cpeGNU-20.10/lib/libcifparse.a(lex.cifp.o):(.bss+0x18): multiple definition of `cifpin'; /scratch/e1000/jenscscs/TestingEB/eiger/9aee7ac-4444/software/Amber/20-3-0-cpeGNU-20.10/lib/libcifparse.a(cifparse.o):(.bss+0x2148): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:173: antechamber] Error 1
```
Do you think that we need a `make clean` before a new configure-make step in the recipe?

**Comment by victorusu** [comment]
@lucamar, I have seen that before. I do you want me to take a look?

**Comment by victorusu** [comment]
> Do you think that we need a make clean before a new configure-make step in the recipe?
@lucamar, I added the `make clean` between steps, because it was failing on Amber 16 and on Amber 18. 
I am not sure if it fails on Amber20. This I haven't tested.

**Comment by lucamar** [comment]
Please go on, your contribution would be very helpful @victorusu!

**Comment by lucamar** [comment]
Unfortunately I still get the same error after inserting `make clean` between steps. See `/scratch/e1000/jenscscs/TestingEB/eiger/6d3ea99-4446/tmp/eb-ym0eAw/easybuild-Amber-20-3-0-20201211.103728.iiphf.log`.

**Comment by lucamar** [comment]
Nope, `make distclean` between steps does not make any difference: see `/scratch/e1000/jenscscs/TestingEB/eiger/ab3ac0c-4447/tmp/eb-Av4wCI/easybuild-Amber-20-3-0-20201211.110409.QWgXe.log`.

**Comment by lucamar** [comment]
I'm closing this pull request since I have opened #2157

**Pull request closed without merging**
