### PR TITLE
[daint-gpu] Vtk 9.1 daint

### PR DESCRIPTION
**Pull request by jfavre**

### CODE REVIEW

**Comment by jfavre** [comment]
retest this please

**Review by lucamar — CHANGES_REQUESTED** [review]
Thanks @jfavre. GitHub reports a conflict with the file `VTK-9.1.0-CrayGNU-20.11-EGL-python3.eb`, would you please be able to fix the conflict and commit again?

**Review by lucamar — APPROVED** [review]
Thanks @jfavre: I have fixed the conflict, please kindly check if the VTK recipe is correct

**Review by jfavre — COMMENTED** [review]
looks good now! hanks @lucamar

**Pull request merged**
