### PR TITLE
[eiger,pilatus] adding 1st version of VisIt for Alps

### PR DESCRIPTION
**Pull request by jfavre**
== COMPLETED: Installation ended successfully (took 1 hour 5 mins 43 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/Visit/3.3.1-cpeGNU-21.12/easybuild/easybuild-Visit-3.3.1-20230110.161632.log
== Build succeeded for 1 out of 1

### CODE REVIEW

**Review by lucamar — CHANGES_REQUESTED** [review]
Thanks @jfavre: please note that the new Visit module will be installed on Eiger as well after merging this pull request, since the production list of Pilatus is just a symbolic link to the one of Eiger. If this is your intention, please add the name Eiger to the title of the pull request, in order to test the build there too.

**Comment by jfavre** [comment]
> Thanks @jfavre: please note that the new Visit module will be installed on Eiger as well after merging this pull request, since the production list of Pilatus is just a symbolic link to the one of Eiger. If this is your intention, please add the name Eiger to the title of the pull request, in order to test the build there too.

Thanks @lucamar . As documented to the linked issues of https://jira.cscs.ch/browse/VCMSA-140, the build is dependent on the installation of further system packages, currently installed manually by Peter Tiernan. So I have consciouly removed the "eiger" name from the title because I know it would fail. It is not clear to me when eiger will receive the same installed software as pilatus.

**Comment by lucamar** [comment]
Thanks for your reply @jfavre: I suggest to wait until the blocking issue [SD-57038](https://jira.cscs.ch/browse/SD-57038) is resolved, in order to test the build on Eiger as well.

**Comment by jfavre** [comment]
retest this please

**Comment by lucamar** [comment]
The configuration error reported by the log file is the following:
```
CMake Error at CMake/FindVisItVTK.cmake:109 (find_package):
  Could not find a package configuration file provided by "VTK" (requested
  version 8.1) with any of the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.
```

**Comment by jfavre** [comment]
the error is due to https://jira.cscs.ch/browse/SD-57287 which I have re-opened since the packet seems to have disappeared after the maintenance.

**Comment by jfavre** [comment]
tested again on uan01

== COMPLETED: Installation ended successfully (took 1 hour 8 mins 27 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/Visit/3.3.1-cpeGNU-21.12/easybuild/easybuild-Visit-3.3.1-20230202.155019.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /run/user/1100/easybuild/tmp/eb-pf1c3kae/easybuild-_fy2hh79.log* have been removed.
== Temporary directory /run/user/1100/easybuild/tmp/eb-pf1c3kae has been removed.

**Comment by jfavre** [comment]
retest this please

**Review by lucamar — APPROVED** [review]
Thanks @jfavre, I have just moved the Visit recipe in the group of GNU ones in the file `jenkins-build`

**Pull request merged**
