### PR TITLE
[daint-gpu] CP2K 7.1 gpu with CrayIntel

### PR DESCRIPTION
**Pull request by lucamar**
Minor change with a fix: adding MKL include and link line options and unloading `cray-libsci` before building.

### CODE REVIEW

**Comment by lucamar** [comment]
retest this please

**Comment by victorusu** [comment]
@lucamar, I just wonder if there was any performance impact by changing from fftw to mkl. Because, GROMACS is slower when using mkl.

**Comment by lucamar** [comment]
> @lucamar, I just wonder if there was any performance impact by changing from fftw to mkl. Because, GROMACS is slower when using mkl.

Thanks for your comment @victorusu: as a matter of fact, I have some performance regression that you can check in https://confluence.cscs.ch/display/GENERAL/CP2K+7.1 vs. https://confluence.cscs.ch/display/GENERAL/CP2K+6.1 and I am still investigating: sure, part of the regression can be due to the MKL FFT, which works otherwise better with other applications.

**Comment by lucamar** [comment]
retest this please

**Pull request merged**
