### PR TITLE
[kesch leone monch] CMake 3.10.0 rc5

### PR DESCRIPTION
**Pull request by lucamar**
Building CMake now requires `-std=c++11`, that is not provided by `GCC 4.4.7` available on the operating system of Kesch, Leone and Monch: therefore on these systems we are forced to build `CMake` using a toolchain providing a more recent version of `GCC` with respect to the `dummy` toolchain.

### CODE REVIEW

**Comment by teojgo** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Pull request merged**
