### PR TITLE
[dom] Python Extensions based on `cray-python`

### PR DESCRIPTION
**Pull request by lucamar**
I propose the name `PyExtensions-%(version)s`, where `%(version)s` is the underlying Python version:
 - I don't mention `python` in the name, the name itself suggests that it is based on Python 
 - the toolchain name `CrayGNU` clarifies that we are on a Cray system, hinting at `cray-python`
 - the toolchain version `17.08` will identify uniquely the version of `cray-python` used as dependency

The extensions built in this recipe are the ones missing from `cray-python` with respect to `Python` modules built on the Cray so far: the list can be extended if needed (e.g. `influxdb`, `pygelf`, ...).

The other recipes included in this pull request are the dependencies of `Python` modules built on Cray systems using EasyBuild: I think we don't have to use them in the recipe `PyExtension`, unless we verify that they are still needed with `cray-python` as well. They might be useful for other `Python` builds.

### CODE REVIEW

**Comment by victorusu** [comment]
@lucamar, is it possible to add to the PyExtensions the following python packages?

pygelf https://pypi.python.org/pypi/pygelf
PyMySQL https://pypi.python.org/pypi/PyMySQL
influxdb https://pypi.python.org/pypi/influxdb/4.1.1

**Comment by jgphpc** [comment]
Unable to locate a modulefile for `EasyBuild-custom/cscs`

**Comment by jgphpc** [comment]
retest this please

**Comment by victorusu** [comment]
If so, the `exts_list` should look like:
```
exts_list = [
     ('Cython', '0.26.1', {
         'source_urls': ['https://pypi.python.org/packages/source/c/cython/'],
     }),
     ('six', '1.10.0', {
         'source_urls': ['https://pypi.python.org/packages/source/s/six/'],
     }),
     ('matplotlib', '2.0.2', {
         'source_urls': ['https://pypi.python.org/packages/source/m/matplotlib/'],
     }),
     ('pandas', '0.20.3', {
         'source_urls': ['https://pypi.python.org/packages/source/p/pandas/'],
     }),
     ('pygelf', '0.3.1', {
         'source_urls': ['https://pypi.python.org/packages/source/p/pygelf/'],
     }),
     ('PyMySQL', '0.7.11', {
         'source_urls': ['https://pypi.python.org/packages/source/p/PyMySQL/'],
     }),
     ('influxdb', '4.1.1', {
         'source_urls': ['https://pypi.python.org/packages/source/i/influxdb/'],
     }),
 ]
```

**Comment by jgphpc** [comment]
`Sanity check failed: sanity checks for ['Cython', 'six', 'matplotlib', 'pandas'] extensions failed!`

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
I don't know why `libpng` failed, I tested the build on a compute node of Dom and the download worked.

**Comment by victorusu** [comment]
retest this please

**Pull request merged**
