### PR TITLE
[dom-gpu] understand/4.x (5 needs new license)

### PR DESCRIPTION
**Pull request by jgphpc**
Will fix https://madra.cscs.ch/scs/doc/issues/345
Need to check license status with Angelo.
https://webrt.cscs.ch/Ticket/Display.html?id=32452

### CODE REVIEW

**Comment by jgphpc** [comment]
retest this please

**Comment by jgphpc** [comment]
TODO: license

**Comment by lucamar** [comment]
You should update the production files as well in this pull request, as this is the targeted release:
```
Understand-4.0.913.eb                              --set-default-module --hidden
```

**Comment by jgphpc** [comment]
> You should update 
will depend on what Angelo will say about the license

**Comment by jgphpc** [comment]
Angelo confirmed we don't have the license for 5.x, i will push the old version.

**Pull request merged**
