### PR TITLE
[fulen]Add gmvolf 16.11 with GCC 6.20 and MVAPICH2.3

### PR DESCRIPTION
**Pull request by victorusu**
This should be compatible with CUDA 9.2 currently installed on Fulen

### CODE REVIEW

**Comment by gppezzi** [comment]
retest this please

**Comment by victorusu** [comment]
retest this please

**Comment by victorusu** [comment]
@gppezzi and @lucamar, this is ready to be merged.

**Comment by victorusu** [comment]
@rsarm, can you take a look at this too?

**Pull request merged**
