### PR TITLE
[daint, dom] Darshan with HDF5 support for PE 20.08

### PR DESCRIPTION
**Pull request by omlins**
Enables HDF5 (cray-hdf5-parallel) instrumentation and setting of log-path by environment variable.

### CODE REVIEW

**Comment by omlins** [comment]
Creates automatically a file with approximately the following naming convention (doc seems outdated)
```
<YEAR>/<MONTH>/<DAY>/<USERNAME>_<BINARY_NAME>_<JOB_ID>_<DATE>_<UNIQUE_ID>_<TIMING>.darshan
```
in $DARSHAN_LOG_DIR_PATH, e.g.:
```
> ls darshan/
omlins_a.out_id1173825_10-8-43724-14494205032741333235_1602151749.darshan
```

**Comment by omlins** [comment]
retest this please

**Comment by omlins** [comment]
If at some point, we decide to set this up to be done automatically for every job in order to get I/O statistics, then one can also set the log file path statically using `--with-log-path=`.

**Review by victorusu — APPROVED** [review]
Thanks @omlins. Great catch! 
`lgtm`

**Pull request merged**
