### PR TITLE
[dom] missing recipes for ParaView 5.9 builds

### PR DESCRIPTION
**Pull request by jfavre**

### CODE REVIEW

**Review by lucamar — COMMENTED** [review]
Thanks @jfavre: you are using `CMake 3.18.4` as builddependency. Is the default `CMake 3.14.5` too old? We can consider updating the default `CMake` version on Dom, if needed.

**Comment by jfavre** [comment]
> Thanks @jfavre: you are using `CMake 3.18.4` as `builddependency`. Is the default `CMake 3.14.5` too old? We can consider updating the default `CMake` version on Dom, if needed.

I forgot the history, why I switched to 3.18.4. I am now re-testing locally with the default CMake

**Comment by jfavre** [comment]
testing with Cmake 3.14.5 was successful. Thanks @lucamar for pointing out this detail.

== COMPLETED: Installation ended successfully (took 31 min 2 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000tds/jfavre/daint/software/ParaView/5.9.0-CrayGNU-20.11-OSMesa-python3/easybuild/easybuild-ParaView-5.9.0-20210309.115103.log

== COMPLETED: Installation ended successfully (took 30 min 47 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000tds/jfavre/daint/software/ParaView/5.9.0-CrayGNU-20.11-EGL-python3/easybuild/easybuild-ParaView-5.9.0-20210309.114430.log

**Comment by jfavre** [comment]
retest this please

**Review by lucamar — APPROVED** [review]
Thanks for checking `CMake` @jfavre

**Comment by lucamar** [comment]
The test failed since Dom was rebooted in the meanwhile, therefore the error reported in the log is expected:
```
Cannot contact dom: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@328eae6f:dom": Remote call on dom failed. The channel is closing down or has closed down
```
See https://jenkins.cscs.ch/blue/organizations/jenkins/TestingEB/detail/TestingEB/4723/pipeline.

**Comment by lucamar** [comment]
retest this please

**Pull request merged**
