### PR TITLE
[dom] libxml2 with cray-python

### PR DESCRIPTION
**Pull request by lucamar**
Usage of `--with-python-install-dir=` to install locally `libxml2.py`: Python bindings of `libxml2` are installed in `EBROOTLIBXML2/lib`, which is added to `LD_LIBRARY_PATH` and `LIBRARY_PATH` by the EasyBuild modulefile.

### CODE REVIEW

**Comment by jfavre** [comment]
I suggest a sanity check

sanity_check_commands = [('python', "-c 'import %(namelower)s'")]

**Comment by jgphpc** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
The build is successful in my environment and the module works as expected in `python`: 
```
$ ls /apps/dom/UES/sandbox/lucamar/easybuild/software/PyExtensions/2.7-CrayGNU-17.08/lib/python2.7/site-packages/
certifi-2017.7.27.1-py2.7.egg         matplotlib-2.0.2-py2.7-linux-x86_64.egg
chardet-3.0.4-py2.7.egg               pandas-0.20.3-py2.7-linux-x86_64.egg
cycler-0.10.0-py2.7.egg               pygelf-0.3.1-py2.7.egg
Cython-0.26.1-py2.7-linux-x86_64.egg  PyMySQL-0.7.11-py2.7.egg
drv_libxml2.py                        pyparsing-2.2.0-py2.7.egg
easy-install.pth                      python_dateutil-2.6.1-py2.7.egg
functools32-3.2.3.post2-py2.7.egg     pytz-2017.2-py2.7.egg
idna-2.6-py2.7.egg                    requests-2.18.4-py2.7.egg
influxdb-4.1.1-py2.7.egg              site.py
libxml2mod.a                          site.pyc
libxml2mod.la                         six-1.10.0-py2.7.egg
libxml2mod.so                         subprocess32-3.2.7-py2.7-linux-x86_64.egg
libxml2.py                            urllib3-1.22-py2.7.egg
libxml2.pyc

python -c "import libxml2"

python
Python 2.7.13 (default, Jun 20 2017, 23:26:04)
[GCC 6.1.0 20160427 (Cray Inc.)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libxml2
>>> libxml2
<module 'libxml2' from '/apps/dom/UES/sandbox/lucamar/easybuild/software/PyExtensions/2.7-CrayGNU-17.08/lib/python2.7/site-packages/libxml2.pyc'>
>>>
```
I need to save the log files to see why the build of user `jenscscs` is not successful on Dom.

**Comment by lucamar** [comment]
I have successfully built `libxml2/2.9.4-CrayGNU-17.08-python2` using username `jenscscs` in `/scratch/snx2000tds/jenscscs/libxml2`:
```
module load libxml2/2.9.4-CrayGNU-17.08-python2

python -c "import libxml2"

python
Python 2.7.13 (default, Jun 20 2017, 23:26:04)
[GCC 6.1.0 20160427 (Cray Inc.)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libxml2
>>> libxml2
<module 'libxml2' from '/scratch/snx2000tds/jenscscs/libxml2/easybuild/software/PyExtensions/2.7-CrayGNU-17.08/lib/python2.7/site-packages/libxml2.pyc'>
``` 
Therefore I will force the build of `PyExtensions` again on Dom using `ProductionEB` and I will retest the build of `libxml2` in this pull request later on.

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
I have copied the log file to `/scratch/snx2000tds/lucamar/libxml2-2.9.4.log` and I clearly see the reason of failure. 

The build needs to write python files for `libxml2` under the production  folders of `PyExtensions`, which are saved under `/apps`, read-only filesystem from compute nodes, where`TestingEB` runs. 

Therefore this test would only succeed if we run on login nodes.

**Pull request merged**
