### PR TITLE
[daint-gpu] [daint-mc] [keschTDS] [leone] [monch] moving vim8 out of /apps/common

### PR DESCRIPTION
**Pull request by jgphpc**

### CODE REVIEW

**Comment by gppezzi** [comment]
retest this please

**Comment by jgphpc** [comment]
Looks ready to be merged: https://jenkins.cscs.ch/job/TestingEB/467/

**Comment by lucamar** [comment]
Do you really need to buil `vim`? You have version `7.4.326` on Dom and Piz Daint

**Comment by jgphpc** [comment]
> Do you really need to buil `vim`? You have version `7.4.326` on Dom and Piz Daint
yes it is a very old version that is incompatible with recent plugins.
you can hide it if you want.

**Pull request merged**
