### PR TITLE
 [pilatus eiger] jupyterlab-4.2.3-cpeGNU-23.12 paths fix - lua

### PR DESCRIPTION
**Pull request by omlins**
This pull request fixes Julia paths, appending IJulia paths rather than prepending:

eiger:
image

pilatus:
image

### CODE REVIEW

**Comment by omlins** [comment]
retest this please

**Review by twrobinson — CHANGES_REQUESTED** [review]
The build didn't complete.

**Review by twrobinson — CHANGES_REQUESTED** [review]
Hi, please add a "Description", detailing the fix, and confirming that it works when tested via jupyter-eiger and jupyter-pilatus GUIs. thanks!

**Comment by omlins** [comment]
retest this please

**Comment by omlins** [comment]
retest this please

**Review by twrobinson — APPROVED** [review]
Looks good now, thanks

**Pull request merged**
