### PR TITLE
[pilatus] Adapting recipes for Intel oneAPI

### PR DESCRIPTION
**Pull request by lucamar**
I have tried to adapt the Intel builds on Pilatus with Cray PE 21.07 to Intel oneAPI using `intel/2021.2.0` (`icx`, `icpx` and `ifort`, since `ifx` is still considered "beta": see the [Porting Guide for ifort to ifx](https://software.intel.com/content/www/us/en/develop/articles/porting-guide-for-ifort-to-ifx.html)). I have also moved outdated recipes to the deprecated folder.

### CODE REVIEW

**Comment by lucamar** [comment]
I have tried to set `CC=cc` in `prebuildopts` for Amber, otherwise the build was failing with the following error message:
```
Obtaining the intel compiler suite versions, e.g.:
     cc -v
Error: cc is not well formed or produces unusual version details!
       Check for a CC environment variable.
Configure failed due to the errors above!
```
However there might be a better way to configure Amber properly, therefore I'm asking @victorusu's review.

**Review by victorusu — APPROVED** [review]
`lgtm`

**Comment by lucamar** [comment]
I have downgraded Amber build with `intel-classic`, but it still fails as it cannot find `bzip2` and MKL FFT: 
```
Checking for libbz2: 
Warning: Could not link to libbz2. Ensure libbz2 libraries/headers are installed.
Warning: Failed command:
     cc  -fPIC -O2 -fp-model fast=2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DBINTRAJ -DHASGZ  -lbz2 -o testp testp.c
Warning: Check bzlib.compile.err for error details.
Warning: Bzip2 compression/decompression not available.

Using FFTW from Intel MKL. Use '-nomklfftw' to prevent this.
Checking that we can use FFTW from Intel MKL: Configuring PMEMD for the MKL FFTW...
Warning:
 Headers and libraries from cray-libsci/21.06.1.1 will be ignored because they conflict with -mkl.

testp.cpp(2): catastrophic error: cannot open source file "fftw3.h"
  #include <fftw3.h>
                    ^

compilation aborted for testp.cpp (code 4)

Error: Could not compile with FFTW from MKL.
Configure failed due to the errors above!
```

**Comment by lucamar** [comment]
I have tried to build the latest AmberTools21 with Amber20 using CMake, but it seems that `COMPILER=CRAY` is poorly supported. I get the following error during the configuration: 
```
 CMake Error at cmake/LibraryTracking.cmake:174 (message):
   Incorrect usage.  At least one LIBRARY should be provided.
 Call Stack (most recent call first):
   cmake/MPIConfig.cmake:122 (import_libraries)
   CMakeLists.txt:118 (include)
```
The same error was reported in a [post on the Amber archive](http://archive.ambermd.org/202008/0093.html), but the solution to use the Intel MPI wrapper did not work for me (see commented lines in the recipe): I could configure, but not build correctly.

**Comment by lucamar** [comment]
I'm merging the pull request, although we need to work on the tentative Amber recipe with Intel OneAPI that I have provided (on purpose, it is not added to any production list).

**Pull request merged**
