### PR TITLE
[dom daint eiger pilatus tsa] Add recipe for ReFrame version 4.0.0-dev.3

### PR DESCRIPTION
**Pull request by jenkins-cscs**

### CODE REVIEW

**Comment by lucamar** [comment]
Ok to test

**Comment by ekouts** [comment]
I think we should probably skip this version since it has an important bug that will affect our tests: https://github.com/reframe-hpc/reframe/issues/2681

**Comment by teojgo** [comment]
> I think we should skip this version since it has an important bug that will affect our tests: [reframe-hpc/reframe#2681](https://github.com/reframe-hpc/reframe/issues/2681)

I think it's ok because we don't deploy the dev versions in any case

**Comment by lucamar** [comment]
Thanks for your comments @ekouts and @teojgo: I will just close the pull request without merging the recipe.

**Pull request closed without merging**
