### PR TITLE
[dom] Add files for PE19.10

### PR DESCRIPTION
**Pull request by ekouts**
Add easyconfigs for cdt/19.10
Fix deprecated easyconfigs
Add metadata for cdt/19.10
Add jenkins files

### CODE REVIEW

**Comment by ekouts** [comment]
So that we don't include the version of an external dependencies when it's the standard.

**Comment by vkarak** [comment]
@lucamar We've discussed this on Friday with @gppezzi and said that it would be better to have different metadata files for each cdt, so as not to grow a single file.

**Comment by ekouts** [comment]
But actually the pull request should not be merged yet because I haven't changed the external dependencies for cray-python in many files. Will do it later on the afternoon.

**Comment by lucamar** [comment]
@ekouts and @vkarak: I agree that it could be better to separate metadata and avoid appending data in a single file. 
However, we will need to have a different metadata file for each system and then export the corresponding variable before loading the EasyBuild custom modulefile, see #1370. 
While it is relatively easy for us to update the variable within the script `production.sh` at each PE update, it might be less immediate for users that load manually EasyBuild on the systems.

**Comment by gppezzi** [comment]
Main goal of having one metadata file per cdt version is to simplify our recipes and allow using versionless external modules as dependency. The cdt module was not available when cray support was designed in EB, now that we have it I think we should try to rely on it in order to optimize our upgrade workflow.

**Comment by lucamar** [comment]
> lgtm. I think we can merge this, can't we?
Yes, we need to merge it to have the correct metadata on Dom after the change of #1370

**Pull request merged**
