### PR TITLE
[dom-gpu] Julia 1.5.0 without cray-libsci_acc module

### PR DESCRIPTION
**Pull request by omlins**
This PR removes the cray-libsci_acc module from the Julia 1.5.0 module as it causes issues with numpy and Dask at runtime in JupyterLab.

### CODE REVIEW

**Review by twrobinson — APPROVED** [review]
great, thanks!

**Comment by omlins** [comment]
retest this please

**Comment by omlins** [comment]
this can be merged right @twrobinson ?

**Comment by omlins** [comment]
@lucamar can you merge?

**Comment by omlins** [comment]
thanks!

**Pull request merged**
