### PR TITLE
[dom] Update ipykernel to PE 19.03

### PR DESCRIPTION
**Pull request by kraushm**

### CODE REVIEW

**Comment by kraushm** [comment]
retest this please

**Comment by lucamar** [comment]
The build failed as the allocation was cancelled on the compute nodes of `Dom`/

**Comment by teojgo** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
The build is fast when performed locally, however it hangs within the Jenkins project.

**Comment by rsarm** [comment]
It seems that a file on `~/cache/pip` was corrupted. Deleting the whole directory solved the problem.

**Pull request merged**
