### PR TITLE
[eiger] ffmpeg 4.4 for eiger

### PR DESCRIPTION
**Pull request by jfavre**
video encoding from still images

### CODE REVIEW

**Comment by victorusu** [comment]
I think the CI error can be avoided if we set `export LMOD_IGNORE_CACHE=1` in the `production.sh` script, before calling`eb ...`.

**Comment by jfavre** [comment]
Thanks @victorusu for your comments. This is beyond my understanding.  I don't understand how yesterday I was able to build the module FFmpeg and to use it, and today, after cleaning up my cache in $EASYBUILD_PREFIX, I can sucessfully build the following modules:

== COMPLETED: Installation ended successfully (took 40 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/NASM/2.15.05-cpeGNU-21.04/easybuild/easybuild-NASM-2.15.05-20210715.085539.log

== COMPLETED: Installation ended successfully (took 32 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/x264/20191217-cpeGNU-21.04/easybuild/easybuild-x264-20191217-20210715.085611.log

== COMPLETED: Installation ended successfully (took 25 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/ogg/1.3.1-cpeGNU-21.04/easybuild/easybuild-ogg-1.3.1-20210715.085636.log

== COMPLETED: Installation ended successfully (took 1 min 23 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/x265/3.2.1-cpeGNU-21.04/easybuild/easybuild-x265-3.2.1-20210715.085759.log

and then it fails finding the module just previously built:

== FAILED: Installation ended unsuccessfully (build directory: /run/user/1100/build/vorbis/1.3.3/cpeGNU-21.04): build failed (first 300 chars): Module command '/usr/share/lmod/lmod/libexec/lmod python load ogg/1.3.1' failed with exit code 1; stderr: Lmod has detected the following error: These module(s) or extension(s) exist but cannot be loaded as requested: "ogg/1.3.1"
   Try: "module spider ogg/1.3.1" to see how to load the module(s).

The hint provided also fails:

module spider ogg/1.3.1
Lmod has detected the following error:  Unable to find: "ogg/1.3.1".

Please advise. TIA

**Comment by jfavre** [comment]
I keep trying to compile the vorbis recipe which fails because it cannot find the off recipe. But eb tells me:

== Temporary log file in case of crash /run/user/1100/tmp/eb-zgjde94h/easybuild-o1gq8tp9.log
== Toolchain/cpeGNU/21.04/ogg/1.3.1 is already installed (module found), skipping
== No easyconfigs left to be built.
== Build succeeded for 0 out of 0

and then tell me it cannot find it

== FAILED: Installation ended unsuccessfully (build directory: /run/user/1100/build/vorbis/1.3.3/cpeGNU-21.04): build failed (first 300 chars): Module command '/usr/share/lmod/lmod/libexec/lmod python load ogg/1.3.1' failed with exit code 1; stderr: Lmod has detected the following error: These module(s) or extension(s) exist but cannot be loaded as requested: "ogg/1.3.1"
   Try: "module spider ogg/1.3.1" to see how to load the module(s).

**Comment by lucamar** [comment]
I think that your build might have hit a known  bug of PE 21.04, which was solved in PE 21.05 and beyond. As a matter of fact, I could build the tool and its dependencies without errors using PE 21.06 instead (the latest currently available on Eiger). 
Therefore, I suggest to provide the recipes for PE 21.06 instead and use UpdateEB for the deployment on the system.

**Review by lucamar — APPROVED** [review]
Thanks @jfavre

**Comment by jfavre** [comment]
thanks @lucamar . I appreciate that you followed up on my problem. It seemed untractable to me.

**Pull request merged**
