### PR TITLE
[dom] Update 7.0.UP03-21.09-daint-mc and 7.0.UP03-21.09-daint-gpu

### PR DESCRIPTION
**Pull request by omlins**

### CODE REVIEW

**Review by victorusu — APPROVED** [review]
`lgtm`

**Comment by victorusu** [comment]
@omlins the `1.6.5` was announced to the users... so probably we need to make sure that @lucamar and @gppezzi are aware of this change...
@lucamar and @gppezzi there is a great reason why @omlins is skipping the installation of 1.6.5. I think we need to updated the announcement about Julia versions. What do you think?

**Comment by omlins** [comment]
See https://git.cscs.ch/ues/userportal/-/merge_requests/582/diffs

**Comment by lucamar** [comment]
@omlins Please add the target systems in the title of the pull request

**Comment by lucamar** [comment]
retest this please

**Pull request merged**
