### PR TITLE
[dom daint eiger pilatus tsa] Add recipe for ReFrame version 3.8.2

### PR DESCRIPTION
**Pull request by jenkins-cscs**

### CODE REVIEW

**Comment by lucamar** [comment]
Ok to test

**Review by vkarak — CHANGES_REQUESTED** [review]
Let's wait before merging this, because I got reports that the current recipes are failing on Daint with the following error:

```
Traceback (most recent call last):
  File "/apps/daint/UES/jenkins/7.0.UP02/reframe/software/reframe/3.7.3/bin/reframe", line 19, in <module>
    import reframe.frontend.cli as cli  # noqa: F401, F403
  File "/apps/daint/UES/jenkins/7.0.UP02/reframe/software/reframe/3.7.3/reframe/frontend/cli.py", line 28, in <module>
    import reframe.frontend.runreport as runreport
  File "/apps/daint/UES/jenkins/7.0.UP02/reframe/software/reframe/3.7.3/reframe/frontend/runreport.py", line 9, in <module>
    import lxml.etree as etree
ModuleNotFoundError: No module named 'lxml.etree'
```

**Comment by haampie** [comment]
See #2487, a conflict would be enough. Didn't see this PR before opening the one about the older reframe release.

**Review by vkarak — APPROVED** [review]

**Review by vkarak — CHANGES_REQUESTED** [review]
We need to incorporate the changes of #2487.

**Comment by teojgo** [comment]
retest this please

**Comment by teojgo** [comment]
@haampie, @vkarak I thinks it's ok now.

**Pull request merged**
