### PR TITLE
[daint dom eiger tsa] Update system_wide.cfg

### PR DESCRIPTION
**Pull request by victorusu**
EasyBuild has updated its list of dependencies for installing the `foss` toolchain. This PR hides most of the "unnecessary" ones
```
UCX
GMP
OpenMPI
PMIx
libpciaccess
Perl
DB
groff
makeinfo
libfabric
UnZip
```

This has the potential to affect the non-Cray systems we have.
For some reason that I am not sure, we do not hide GMP on Daint.
So, this PR also affects Daint.

### CODE REVIEW

**Comment by kraushm** [comment]
On the machines with FOSS (at least the ones I'm aware of) the recommended workflow is through meta-modules for the tool chains instead of loading the single modules like `OpenMPI`. Hence, I would assume these should not be affected immediately.

Does this PR require the software stack to be redeployed anew or is this optional?

**Comment by victorusu** [comment]
It is optional

**Comment by lucamar** [comment]
retest this please

**Comment by lucamar** [comment]
retest this please

**Review by lucamar — APPROVED** [review]
Please @kraushm @gppezzi let me know if we can merge this pull request

**Review by kraushm — APPROVED** [review]
lgtm.

**Pull request merged**
